# pipeline_type dictates how Zen will treat your repository.
# maven_docker means this is a Java project that will be built with
# "mvn clean install" in a drone-managed container.
pipeline_type: maven_docker

# for Zen workflow V2
version: 2.0

# These maven profiles, if present in your POM, will be explicitly
# activated by Zen.
# zen-jacoco is not marked active in your POM, so will not be used
# outside of Zen builds.
active_profiles: zen,zen-jacoco

# If the maven build succeeds, a code coverage test is performed using Jacoco.
# If Jacoco determines that the code coverage is less than this percentage, the
# build will be deemed unsuccessful, despite compilation and tests succeeding.
# (A value of zero disables the code coverage step.)
minimum_code_coverage_percentage: 0

# Content between here and the end of the file, while it must be valid YAML,
# is currently read textually by Zen. The order of the sections cannot change.
itest:
  codeline: main
  modules:
    aura:
      optional_history_file: null
      properties_name: aura.version
  ftest_labels: [~ignore,precheckin]
  ab_enabled: false

script:
  localedef -v -c -i en_US -f UTF-8 en_US.UTF-8
  rm -r {node,node_modules} || true
  wget --quiet --recursive --no-parent --reject "index.html*" --level=99 http://localhost/node_modules/ || true
  wget --quiet --recursive --no-parent --reject "index.html*" --level=99 http://localhost/node/ || true
  chmod -R 0755 localhost
  sudo unmount /dev/shm
  sudo mount -t tmpfs -o rw,nosuid,nodev,noexec,relatime,size=512M,tmpfs /dev/shm
  mv localhost/* .
  cp settings.xml /home/mvn-user/.m2/settings.xml
  chown -R mvn-user /home/mvn-user/.m2
  chown -R mvn-user $(pwd)
  status=0
  sudo -iu mvn-user bash -c "cd $(pwd);mvn clean deploy $MAVEN_ARGS -Dmaven.repo.local=$(pwd)/.m2/repository -DaltDeploymentRepository=zen::default::file://$(pwd)/$LOCAL_DEPLOY_DIR -Dnode.download.root.url=http://localhost/node/ -Dchromedriver.download.root.url=http://localhost/chromedriver -Dnpm.download.root.url=http://localhost/npm/ -Deslint.enabled" || export status=$? || true
  [ ${status} -eq 0 ] && sudo -iu mvn-user bash -c "cd $(pwd);set -x;export LANG=\"en_US.UTF-8\";mvn verify $MAVEN_ARGS -Dmaven.repo.local=$(pwd)/.m2/repository -DaltDeploymentRepository=zen::default::file://$(pwd)/$LOCAL_DEPLOY_DIR -Dnode.download.root.url=http://localhost/node/ -Dchromedriver.download.root.url=http://localhost/chromedriver -Dnpm.download.root.url=http://localhost/npm/ -Pdesktop -DskipJsDoc -DskipComponentCompile -DskipUnitTests -DrunIntTests -Dwebdriver.browser.type=GOOGLECHROME -Dwebdriver.chrome.nosandbox=true -Dwebdriver.reusebrowser=true -Dwebdriver.timeout=90 -Dwebdriver.timeout.getdriver=30 -DtestThreadCount=3" || export status=$? || true
  chown -R $ORIG_UID:$ORIG_UID $(pwd)
  exit ${status:-0}
# It is currently required that there be an empty line following the script: section

# Everything from here to the end of the file is used as a .drone.yml file. In the drone
# container, the commands in the script: section will be executed. No Zen-specific content
# can be added.
build:
  image: ops0-artifactrepo1-0-prd.data.sfdc.net/dci/centos-aura-tools:aura0.6000@sha256:202bf39687fcee3f9175cd4741025b5af62c30396e7dc0a3d01e97d6b0ec9247
  auth_config:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
  environment:
    ORIG_UID: $$UID
    MAVEN_ARGS: $$MAVEN_ARGS
    LOCAL_DEPLOY_DIR: $$LOCAL_DEPLOY_DIR
  extra_hosts:
    - external-tools
  commands:
    - ./.zenbuild.sh
compose:
  external-tools:
    image: ops0-artifactrepo1-0-prd.data.sfdc.net/dci/alpine-aura-tools-external:0.6000@sha256:4f251c65452108fe7de7bbe6de15669f8896796dc2995da85c73ac87a938e726
    auth_config:
      username: $$DOCKER_USERNAME
      password: $$DOCKER_PASSWORD
