({
    testName: {
        "systemAPI": "HTMLElement",
        "secureAPI": "SecureElement"
    },
    tagNames: [
        "A",
        "AREA",
        "AUDIO",
        "BASE",
        "BDO",
        "BUTTON",
        "CANVAS",
        "CAPTION",
        "COL",
        "COLGROUP",
        "DATA",
        "DEL",
        "DETAILS",
        "EMBED",
        "FIELDSET",
        "FORM",
        "IFRAME",
        "IMG",
        "INPUT",
        "INS",
        "LABEL",
        "LI",
        "LINK",
        "MAP",
        "META",
        "METER",
        "OBJECT",
        "OL",
        "OPTGROUP",
        "OPTION",
        "OUTPUT",
        "PARAM",
        "PROGRESS",
        "Q",
        "SELECT",
        "SOURCE",
        "TABLE",
        "TBODY",
        "TD",
        "TFOOT",
        "TEMPLATE",
        "TEXTAREA",
        "TH",
        "THEAD",
        "TIME",
        "TR",
        "TRACK",
        "VIDEO"
    ],
    svgTagNames: [
        "SVG"
    ],
    testPlan: {
	    "HTMLAnchorElement": {
	        "charset":                        { type: "string" },
	        "coords":                         { type: "string" },
	        "download":                       { type: "string" },
	        "hash":                           { type: "string" },
	        "host":                           { type: "string" },
	        "hostname":                       { type: "string" },
	        "href":                           { type: "string" },
	        "hreflang":                       { type: "string" },
	        "name":                           { type: "string" },
	        "origin":                         { type: "string" },
	        "password":                       { type: "string" },
	        "pathname":                       { type: "string" },
	        "ping":                           { type: "string" },
	        "port":                           { type: "string" },
	        "protocol":                       { type: "string" },
	        "referrerPolicy":                 { type: "string" },
	        "rel":                            { type: "string" },
	        "rev":                            { type: "string" },
	        "search":                         { type: "string" },
	        "shape":                          { type: "string" },
	        "target":                         { type: "string" },
	        "text":                           { type: "string" },
	        "type":                           { type: "string" },
	        "username":                       { type: "string" }
	    },
	    "HTMLAreaElement": {
	        "alt":                            { type: "string" },
	        "coords":                         { type: "string" },
	        "hash":                           { type: "string" },
	        "host":                           { type: "string" },
	        "hostname":                       { type: "string" },
	        "href":                           { type: "string" },
	        "noHref":                         { type: "boolean" },
	        "origin":                         { type: "string" },
	        "password":                       { type: "string" },
	        "pathname":                       { type: "string" },
	        "ping":                           { type: "string" },
	        "port":                           { type: "string" },
	        "protocol":                       { type: "string" },
	        "referrerPolicy":                 { type: "string" },
	        "search":                         { type: "string" },
	        "shape":                          { type: "string" },
	        "target":                         { type: "string" },
	        "username":                       { type: "string" }
	    },
	    "HTMLAudioElement": {
	    },
	    "HTMLMediaElement": {
	        "HAVE_CURRENT_DATA":              { type: "number" },
	        "HAVE_ENOUGH_DATA":               { type: "number" },
	        "HAVE_FUTURE_DATA":               { type: "number" },
	        "HAVE_METADATA":                  { type: "number" },
	        "HAVE_NOTHING":                   { type: "number" },
	        "NETWORK_EMPTY":                  { type: "number" },
	        "NETWORK_IDLE":                   { type: "number" },
	        "NETWORK_LOADING":                { type: "number" },
	        "NETWORK_NO_SOURCE":              { type: "number" },
	        "addTextTrack":                   { type: "function" },
	        "autoplay":                       { type: "boolean" },
	        "buffered":                       { type: "TimeRanges" },
	        "canPlayType":                    { type: "function" },
	        "controls":                       { type: "boolean" },
	        "crossOrigin":                    { type: "Null" },
	        "currentSrc":                     { type: "string" },
	        "currentTime":                    { type: "number" },
	        "defaultMuted":                   { type: "boolean" },
	        "defaultPlaybackRate":            { type: "number" },
	        "disableRemotePlayback":          { type: "boolean" },
	        "duration":                       { type: "number" },
	        "ended":                          { type: "boolean" },
	        "error":                          { type: "Null" },
	        "load":                           { type: "function" },
	        "loop":                           { type: "boolean" },
	        "mediaKeys":                      { type: "Null" },
	        "muted":                          { type: "boolean" },
	        "networkState":                   { type: "number" },
	        "onencrypted":                    { type: "@event" },
	        "pause":                          { type: "function" },
	        "paused":                         { type: "boolean" },
	        "play":                           { type: "function" },
	        "playbackRate":                   { type: "number" },
	        "played":                         { type: "TimeRanges" },
	        "preload":                        { type: "string" },
	        "readyState":                     { type: "number" },
	        "seekable":                       { type: "TimeRanges" },
	        "seeking":                        { type: "boolean" },
	        "setMediaKeys":                   { type: "function" },
	        "setSinkId":                      { type: "function" },
	        "sinkId":                         { type: "string" },
	        "src":                            { type: "string" },
	        "textTracks":                     { type: "TextTrackList" },
	        "volume":                         { type: "number" },
	        "webkitAudioDecodedByteCount":    { type: "number" },
	        "webkitVideoDecodedByteCount":    { type: "number" }
	    },
	    "HTMLBaseElement": {
	        "href":                           { type: "string" },
	        "target":                         { type: "string" }
	    },
	    "HTMLButtonElement": {
	        "autofocus":                      { type: "boolean" },
	        "checkValidity":                  { type: "function" },
	        "disabled":                       { type: "boolean" },
	        "form":                           { type: "Null" },
	        "formAction":                     { type: "string" },
	        "formEnctype":                    { type: "string" },
	        "formMethod":                     { type: "string" },
	        "formNoValidate":                 { type: "boolean" },
	        "formTarget":                     { type: "string" },
	        "labels":                         { type: "NodeList" },
	        "name":                           { type: "string" },
	        "reportValidity":                 { type: "function" },
	        "setCustomValidity":              { type: "function" },
	        "type":                           { type: "string" },
	        "validationMessage":              { type: "string" },
	        "validity":                       { type: "ValidityState" },
	        "value":                          { type: "string" },
	        "willValidate":                   { type: "boolean" }
	    },
	    "HTMLCanvasElement": {
	        "captureStream":                  { type: "function" },
	        "getContext":                     { type: "function" },
	        "height":                         { type: "number" },
	        "toBlob":                         { type: "function" },
	        "toDataURL":                      { type: "function" },
	        "width":                          { type: "number" }
	    },
	    "HTMLTableColElement": {
	        "align":                          { type: "string" },
	        "ch":                             { type: "string" },
	        "chOff":                          { type: "string" },
	        "span":                           { type: "number" },
	        "vAlign":                         { type: "string" },
	        "width":                          { type: "string" }
	    },
	    "HTMLTableElement": {
	        "caption":                        { type: "string" },
	        "tHead":                          { type: "Null", skipOpaque : true },
	        "tFoot":                          { type: "Null", skipOpaque : true },
	        "tBodies":                        { type: "HTMLCollection" },
	        "createTHead":                    { type: "function" },
	        "deleteTHead":                    { type: "function" },
	        "createTFoot":                    { type: "function" },
	        "deleteTFoot":                    { type: "function" },
	        "createCaption":                  { type: "function" },
	        "deleteCaption":                  { type: "function" },
	        "rows":                           { type: "HTMLCollection" },
	        "insertRow":                      { type: "function" },
	        "deleteRow":                      { type: "function" },
	        "width":                          { type: "string" }
	    },
	    "HTMLTableRowElement": {
	        "cells":                          { type: "HTMLCollection" },
	        "rowIndex":                       { type: "number" },
	        "sectionRowIndex":                { type: "number" },
		    "insertCell":                     { type: "function" },
	        "deleteCell":                     { type: "function" }        
	    },
	    "HTMLTableSectionElement": {
	        "rows":                           { type: "HTMLCollection" },
	        "insertRow":                      { type: "function" },
	        "deleteRow":                      { type: "function" }
	    },
	    "HTMLUnknownElement": {
	    },
	    "HTMLModElement": {
	        "cite":                           { type: "string" },
	        "dateTime":                       { type: "string" }
	    },
	    "HTMLDetailsElement": {
	        "open":                           { type: "boolean" }
	    },
	    "HTMLEmbedElement": {
	        "align":                          { type: "string" },
	        "getSVGDocument":                 { type: "function" },
	        "height":                         { type: "string" },
	        "name":                           { type: "string" },
	        "src":                            { type: "string" },
	        "type":                           { type: "string" },
	        "width":                          { type: "string" }
	    },
	    "HTMLFieldSetElement": {
	        "checkValidity":                  { type: "function" },
	        "disabled":                       { type: "boolean" },
	        "elements":                       { type: "HTMLFormControlsCollection" },
	        "form":                           { type: "Null" },
	        "name":                           { type: "string" },
	        "reportValidity":                 { type: "function" },
	        "setCustomValidity":              { type: "function" },
	        "type":                           { type: "string" },
	        "validationMessage":              { type: "string" },
	        "validity":                       { type: "ValidityState" },
	        "willValidate":                   { type: "boolean" }
	    },
	    "HTMLFormElement": {
	        "acceptCharset":                  { type: "string" },
	        "action":                         { type: "string" },
	        "autocomplete":                   { type: "string" },
	        "checkValidity":                  { type: "function" },
	        "elements":                       { type: "HTMLFormControlsCollection" },
	        "encoding":                       { type: "string" },
	        "enctype":                        { type: "string" },
	        "length":                         { type: "number" },
	        "method":                         { type: "string" },
	        "name":                           { type: "string" },
	        "noValidate":                     { type: "boolean" },
	        "reportValidity":                 { type: "function" },
	        "requestAutocomplete":            { type: "function" },
	        "reset":                          { type: "function" },
	        "submit":                         { type: "function" },
	        "target":                         { type: "string" }
	    },
	    "HTMLIFrameElement": {
            "align":                          { type: "string" },
            "allowFullscreen":                { type: "boolean" },
            "contentDocument":                { type: "Null", support: false },
            "contentWindow":                  { type: "Window" },
            "frameBorder":                    { type: "string" },
            "getSVGDocument":                 { type: "function", support: false },
            "height":                         { type: "string" },
            "longDesc":                       { type: "string" },
            "marginHeight":                   { type: "string" },
            "marginWidth":                    { type: "string" },
            "name":                           { type: "string" },
            "referrerPolicy":                 { type: "string" },
            "sandbox":                        { type: "DOMTokenList", support: false },
            "scrolling":                      { type: "string" },
            "src":                            { type: "string" },
            "srcdoc":                         { type: "string", support: false },
            "width":                          { type: "string" }
        },
	    "HTMLImageElement": {
	        "align":                          { type: "string" },
	        "alt":                            { type: "string" },
	        "border":                         { type: "string" },
	        "complete":                       { type: "boolean" },
	        "crossOrigin":                    { type: "Null" },
	        "currentSrc":                     { type: "string" },
	        "height":                         { type: "number" },
	        "hspace":                         { type: "number" },
	        "isMap":                          { type: "boolean" },
	        "longDesc":                       { type: "string" },
	        "lowsrc":                         { type: "string" },
	        "name":                           { type: "string" },
	        "naturalHeight":                  { type: "number" },
	        "naturalWidth":                   { type: "number" },
	        "referrerPolicy":                 { type: "string" },
	        "sizes":                          { type: "string" },
	        "src":                            { type: "string" },
	        "srcset":                         { type: "string" },
	        "useMap":                         { type: "string" },
	        "vspace":                         { type: "number" },
	        "width":                          { type: "number" },
	        "x":                              { type: "number" },
	        "y":                              { type: "number" }
	    },
	    "HTMLInputElement": {
	        "accept":                         { type: "string" },
	        "align":                          { type: "string" },
	        "alt":                            { type: "string" },
	        "autocapitalize":                 { type: "string" },
	        "autocomplete":                   { type: "string" },
	        "autofocus":                      { type: "boolean" },
	        "checkValidity":                  { type: "function" },
	        "checked":                        { type: "boolean" },
	        "defaultChecked":                 { type: "boolean" },
	        "defaultValue":                   { type: "string" },
	        "dirName":                        { type: "string" },
	        "disabled":                       { type: "boolean" },
	        "files":                          { type: "Null" },
	        "form":                           { type: "Null" },
	        "formAction":                     { type: "string" },
	        "formEnctype":                    { type: "string" },
	        "formMethod":                     { type: "string" },
	        "formNoValidate":                 { type: "boolean" },
	        "formTarget":                     { type: "string" },
	        "height":                         { type: "number" },
	        "incremental":                    { type: "boolean" },
	        "indeterminate":                  { type: "boolean" },
	        "labels":                         { type: "NodeList" },
	        "list":                           { type: "Null" },
	        "max":                            { type: "string" },
	        "maxLength":                      { type: "number" },
	        "min":                            { type: "string" },
	        "minLength":                      { type: "number" },
	        "multiple":                       { type: "boolean" },
	        "name":                           { type: "string" },
	        "pattern":                        { type: "string" },
	        "placeholder":                    { type: "string" },
	        "readOnly":                       { type: "boolean" },
	        "reportValidity":                 { type: "function" },
	        "required":                       { type: "boolean" },
	        "select":                         { type: "function" },
	        "selectionDirection":             { type: "string" },
	        "selectionEnd":                   { type: "number" },
	        "selectionStart":                 { type: "number" },
	        "setCustomValidity":              { type: "function" },
	        "setRangeText":                   { type: "function" },
	        "setSelectionRange":              { type: "function" },
	        "size":                           { type: "number" },
	        "src":                            { type: "string" },
	        "step":                           { type: "string" },
	        "stepDown":                       { type: "function" },
	        "stepUp":                         { type: "function" },
	        "type":                           { type: "string" },
	        "useMap":                         { type: "string" },
	        "validationMessage":              { type: "string" },
	        "validity":                       { type: "ValidityState" },
	        "value":                          { type: "string" },
	        "valueAsDate":                    { type: "Null" },
	        "valueAsNumber":                  { type: "number" },
	        "webkitEntries":                  { type: "Array" },
	        "webkitdirectory":                { type: "boolean" },
	        "width":                          { type: "number" },
	        "willValidate":                   { type: "boolean" }
	    },
	    "HTMLLabelElement": {
	        "control":                        { type: "Null" },
	        "form":                           { type: "Null" },
	        "htmlFor":                        { type: "string" }
	    },
	    "HTMLLIElement": {
	        "type":                           { type: "string" },
	        "value":                          { type: "number" }
	    },
	    "HTMLLinkElement": {
	        "as":                             { type: "string" },
	        "charset":                        { type: "string" },
	        "crossOrigin":                    { type: "Null" },
	        "disabled":                       { type: "boolean" },
	        "href":                           { type: "string" },
	        "hreflang":                       { type: "string" },
	        "import":                         { type: "Null" },
	        "integrity":                      { type: "string" },
	        "media":                          { type: "string" },
	        "rel":                            { type: "string" },
	        "relList":                        { type: "DOMTokenList" },
	        "rev":                            { type: "string" },
	        "sheet":                          { type: "Null" },
	        "sizes":                          { type: "DOMTokenList" },
	        "target":                         { type: "string" },
	        "type":                           { type: "string" }
	    },
	    "HTMLMapElement": {
	        "areas":                          { type: "HTMLCollection" },
	        "name":                           { type: "string" }
	    },
	    "HTMLMetaElement": {
	        "content":                        { type: "string" },
	        "httpEquiv":                      { type: "string" },
	        "name":                           { type: "string" },
	        "scheme":                         { type: "string" }
	    },
	    "HTMLMeterElement": {
	        "high":                           { type: "number" },
	        "labels":                         { type: "NodeList" },
	        "low":                            { type: "number" },
	        "max":                            { type: "number" },
	        "min":                            { type: "number" },
	        "optimum":                        { type: "number" },
	        "value":                          { type: "number" }
	    },
	    "HTMLObjectElement": {
	        "align":                          { type: "string" },
	        "archive":                        { type: "string" },
	        "border":                         { type: "string" },
	        "checkValidity":                  { type: "function" },
	        "code":                           { type: "string" },
	        "codeBase":                       { type: "string" },
	        "codeType":                       { type: "string" },
	        "contentDocument":                { type: "Null" },
	        "data":                           { type: "string" },
	        "declare":                        { type: "boolean" },
	        "form":                           { type: "Null" },
	        "getSVGDocument":                 { type: "function" },
	        "height":                         { type: "string" },
	        "hspace":                         { type: "number" },
	        "name":                           { type: "string" },
	        "reportValidity":                 { type: "function" },
	        "setCustomValidity":              { type: "function" },
	        "standby":                        { type: "string" },
	        "type":                           { type: "string" },
	        "useMap":                         { type: "string" },
	        "validationMessage":              { type: "string" },
	        "validity":                       { type: "ValidityState" },
	        "vspace":                         { type: "number" },
	        "width":                          { type: "string" },
	        "willValidate":                   { type: "boolean" }
	    },
	    "HTMLOListElement": {
	        "compact":                        { type: "boolean" },
	        "reversed":                       { type: "boolean" },
	        "start":                          { type: "number" },
	        "type":                           { type: "string" }
	    },
	    "HTMLOptGroupElement": {
	        "disabled":                       { type: "boolean" },
	        "label":                          { type: "string" }
	    },
	    "HTMLOptionElement": {
	        "defaultSelected":                { type: "boolean" },
	        "disabled":                       { type: "boolean" },
	        "form":                           { type: "Null" },
	        "index":                          { type: "number" },
	        "label":                          { type: "string" },
	        "selected":                       { type: "boolean" },
	        "text":                           { type: "string" },
	        "value":                          { type: "string" }
	    },
	    "HTMLOutputElement": {
	        "checkValidity":                  { type: "function" },
	        "defaultValue":                   { type: "string" },
	        "form":                           { type: "Null" },
	        "htmlFor":                        { type: "DOMTokenList" },
	        "labels":                         { type: "NodeList" },
	        "name":                           { type: "string" },
	        "reportValidity":                 { type: "function" },
	        "setCustomValidity":              { type: "function" },
	        "type":                           { type: "string" },
	        "validationMessage":              { type: "string" },
	        "validity":                       { type: "ValidityState" },
	        "value":                          { type: "string" },
	        "willValidate":                   { type: "boolean" }
	    },
	    "HTMLParamElement": {
	        "name":                           { type: "string" },
	        "type":                           { type: "string" },
	        "value":                          { type: "string" },
	        "valueType":                      { type: "string" }
	    },
	    "HTMLProgressElement": {
	        "labels":                         { type: "NodeList" },
	        "max":                            { type: "number" },
	        "position":                       { type: "number" },
	        "value":                          { type: "number" }
	    },
	    "HTMLQuoteElement": {
	        "cite":                           { type: "string" }
	    },
	    "HTMLSelectElement": {
	        "add":                            { type: "function" },
	        "autofocus":                      { type: "boolean" },
	        "checkValidity":                  { type: "function" },
	        "disabled":                       { type: "boolean" },
	        "form":                           { type: "Null" },
	        "item":                           { type: "function" },
	        "labels":                         { type: "NodeList" },
	        "length":                         { type: "number" },
	        "multiple":                       { type: "boolean" },
	        "name":                           { type: "string" },
	        "namedItem":                      { type: "function" },
	        "options":                        { type: "HTMLOptionsCollection" },
	        "remove":                         { type: "function" },
	        "reportValidity":                 { type: "function" },
	        "required":                       { type: "boolean" },
	        "selectedIndex":                  { type: "number" },
	        "selectedOptions":                { type: "HTMLCollection" },
	        "setCustomValidity":              { type: "function" },
	        "size":                           { type: "number" },
	        "type":                           { type: "string" },
	        "validationMessage":              { type: "string" },
	        "validity":                       { type: "ValidityState" },
	        "value":                          { type: "string" },
	        "willValidate":                   { type: "boolean" }
	    },
	    "HTMLSourceElement": {
	        "media":                          { type: "string" },
	        "sizes":                          { type: "string" },
	        "src":                            { type: "string" },
	        "srcset":                         { type: "string" },
	        "type":                           { type: "string" }
	    },
	    "HTMLTableCellElement": {
	        "abbr":                           { type: "string" },
	        "align":                          { type: "string" },
	        "axis":                           { type: "string" },
	        "bgColor":                        { type: "string" },
	        "cellIndex":                      { type: "number" },
	        "ch":                             { type: "string" },
	        "chOff":                          { type: "string" },
	        "colSpan":                        { type: "number" },
	        "headers":                        { type: "string" },
	        "height":                         { type: "string" },
	        "noWrap":                         { type: "boolean" },
	        "rowSpan":                        { type: "number" },
	        "scope":                          { type: "string" },
	        "vAlign":                         { type: "string" },
	        "width":                          { type: "string" }
	    },
	    "HTMLTemplateElement": {
	        "content":                        { type: "DocumentFragment" }
	    },
	    "HTMLTextAreaElement": {
	        "autocapitalize":                 { type: "string" },
	        "autofocus":                      { type: "boolean" },
	        "checkValidity":                  { type: "function" },
	        "cols":                           { type: "number" },
	        "defaultValue":                   { type: "string" },
	        "dirName":                        { type: "string" },
	        "disabled":                       { type: "boolean" },
	        "form":                           { type: "Null" },
	        "labels":                         { type: "NodeList" },
	        "maxLength":                      { type: "number" },
	        "minLength":                      { type: "number" },
	        "name":                           { type: "string" },
	        "placeholder":                    { type: "string" },
	        "readOnly":                       { type: "boolean" },
	        "reportValidity":                 { type: "function" },
	        "required":                       { type: "boolean" },
	        "rows":                           { type: "number" },
	        "select":                         { type: "function" },
	        "selectionDirection":             { type: "string" },
	        "selectionEnd":                   { type: "number" },
	        "selectionStart":                 { type: "number" },
	        "setCustomValidity":              { type: "function" },
	        "setRangeText":                   { type: "function" },
	        "setSelectionRange":              { type: "function" },
	        "textLength":                     { type: "number" },
	        "type":                           { type: "string" },
	        "validationMessage":              { type: "string" },
	        "validity":                       { type: "ValidityState" },
	        "value":                          { type: "string" },
	        "willValidate":                   { type: "boolean" },
	        "wrap":                           { type: "string" }
	    },
	    "HTMLTrackElement": {
	        "ERROR":                          { type: "number" },
	        "LOADED":                         { type: "number" },
	        "LOADING":                        { type: "number" },
	        "NONE":                           { type: "number" },
	        "default":                        { type: "boolean" },
	        "kind":                           { type: "string" },
	        "label":                          { type: "string" },
	        "readyState":                     { type: "number" },
	        "src":                            { type: "string" },
	        "srclang":                        { type: "string" },
	        "track":                          { type: "TextTrack" }
	    },
	    "HTMLVideoElement": {
	        "height":                         { type: "number" },
	        "poster":                         { type: "string" },
	        "videoHeight":                    { type: "number" },
	        "videoWidth":                     { type: "number" },
	        "webkitDecodedFrameCount":        { type: "number", support: false  },
	        "webkitDisplayingFullscreen":     { type: "boolean", support: false  },
	        "webkitDroppedFrameCount":        { type: "number", support: false  },
	        "webkitEnterFullScreen":          { type: "function", support: false  },
	        "webkitEnterFullscreen":          { type: "function", support: false  },
	        "webkitExitFullScreen":           { type: "function", support: false  },
	        "webkitExitFullscreen":           { type: "function", support: false  },
	        "webkitSupportsFullscreen":       { type: "boolean", support: false  },
	        "width":                          { type: "number" }
	    },
	    "HTMLElement": {
	        "accessKey":                      { type: "string" },
	        "blur":                           { type: "function" },
	        "click":                          { type: "function" },
	        "contentEditable":                { type: "string" },
	        "dataset":                        { type: "DOMStringMap" },
	        "dir":                            { type: "string" },
	        "draggable":                      { type: "boolean" },
	        "focus":                          { type: "function" },
	        "hidden":                         { type: "boolean" },
	        "innerText":                      { type: "string" },
	        "isContentEditable":              { type: "boolean" },
	        "lang":                           { type: "string" },
	        "offsetHeight":                   { type: "number" },
	        "offsetLeft":                     { type: "number" },
	        "offsetParent":                   { type: "Null" },
	        "offsetTop":                      { type: "number" },
	        "offsetWidth":                    { type: "number" },
	        "onabort":                        { type: "@event" },
	        "onautocomplete":                 { type: "@event" },
	        "onautocompleteerror":            { type: "@event" },
	        "onblur":                         { type: "@event" },
	        "oncancel":                       { type: "@event" },
	        "oncanplay":                      { type: "@event" },
	        "oncanplaythrough":               { type: "@event" },
	        "onchange":                       { type: "@event" },
	        "onclick":                        { type: "@event" },
	        "onclose":                        { type: "@event" },
	        "oncontextmenu":                  { type: "@event" },
	        "oncuechange":                    { type: "@event" },
	        "ondblclick":                     { type: "@event" },
	        "ondrag":                         { type: "@event" },
	        "ondragend":                      { type: "@event" },
	        "ondragenter":                    { type: "@event" },
	        "ondragleave":                    { type: "@event" },
	        "ondragover":                     { type: "@event" },
	        "ondragstart":                    { type: "@event" },
	        "ondrop":                         { type: "@event" },
	        "ondurationchange":               { type: "@event" },
	        "onemptied":                      { type: "@event" },
	        "onended":                        { type: "@event" },
	        "onerror":                        { type: "@event" },
	        "onfocus":                        { type: "@event" },
	        "oninput":                        { type: "@event" },
	        "oninvalid":                      { type: "@event" },
	        "onkeydown":                      { type: "@event" },
	        "onkeypress":                     { type: "@event" },
	        "onkeyup":                        { type: "@event" },
	        "onload":                         { type: "@event" },
	        "onloadeddata":                   { type: "@event" },
	        "onloadedmetadata":               { type: "@event" },
	        "onloadstart":                    { type: "@event" },
	        "onmousedown":                    { type: "@event" },
	        "onmouseenter":                   { type: "@event" },
	        "onmouseleave":                   { type: "@event" },
	        "onmousemove":                    { type: "@event" },
	        "onmouseout":                     { type: "@event" },
	        "onmouseover":                    { type: "@event" },
	        "onmouseup":                      { type: "@event" },
	        "onmousewheel":                   { type: "@event" },
	        "onpause":                        { type: "@event" },
	        "onplay":                         { type: "@event" },
	        "onplaying":                      { type: "@event" },
	        "onprogress":                     { type: "@event" },
	        "onratechange":                   { type: "@event" },
	        "onreset":                        { type: "@event" },
	        "onresize":                       { type: "@event" },
	        "onscroll":                       { type: "@event" },
	        "onseeked":                       { type: "@event" },
	        "onseeking":                      { type: "@event" },
	        "onselect":                       { type: "@event" },
	        "onshow":                         { type: "@event" },
	        "onstalled":                      { type: "@event" },
	        "onsubmit":                       { type: "@event" },
	        "onsuspend":                      { type: "@event" },
	        "ontimeupdate":                   { type: "@event" },
	        "ontoggle":                       { type: "@event" },
	        "ontouchcancel":               	  { type: "@event" },
	        "ontouchend":                	  { type: "@event" },
	        "ontouchmove":                	  { type: "@event" },
	        "ontouchstart":                	  { type: "@event" },
	        "onvolumechange":                 { type: "@event" },
	        "onwaiting":                      { type: "@event" },
	        "outerText":                      { type: "string" },
	        "spellcheck":                     { type: "boolean" },
	        "style":                          { type: "CSSStyleDeclaration" },
	        "tabIndex":                       { type: "number" },
	        "title":                          { type: "string" },
	        "translate":                      { type: "boolean" }
	    },
	    "SVGElement": {
	    	"blur":							  { type: "function" },
	    	"focus": 					      { type: "function" },
	    	"ownerSVGElement": 				  { type: "Null", skipOpaque : true },
	    	"onabort":                     	  { type: "@event" },
	    	"onblur":                         { type: "@event" },
	    	"oncancel":                       { type: "@event" },
	    	"oncanplay":                      { type: "@event" },
	    	"oncanplaythrough":               { type: "@event" },
	    	"onchange":                       { type: "@event" },
	    	"onclick":                        { type: "@event" },
	    	"onclose":                        { type: "@event" },
	    	"oncontextmenu":                  { type: "@event" },
	    	"oncuechange":                    { type: "@event" },
	    	"ondblclick":                     { type: "@event" },
	    	"ondrag":                         { type: "@event" },
	    	"ondragend":                      { type: "@event" },
	    	"ondragenter":                    { type: "@event" },
	    	"ondragleave":                    { type: "@event" },
	    	"ondragover":                     { type: "@event" },
	    	"ondragstart":                    { type: "@event" },
	    	"ondrop":                         { type: "@event" },
	    	"ondurationchange":               { type: "@event" },
	    	"onemptied":                      { type: "@event" },
	    	"onended":                        { type: "@event" },
	    	"onerror":                        { type: "@event" },
	    	"onfocus":                        { type: "@event" },
	    	"oninput":                        { type: "@event" },
	    	"oninvalid":                      { type: "@event" },
	    	"onkeydown":                      { type: "@event" },
	    	"onkeypress":                     { type: "@event" },
	    	"onkeyup":                        { type: "@event" },
	    	"onload":                         { type: "@event" },
	    	"onloadeddata":                   { type: "@event" },
	    	"onloadedmetadata":               { type: "@event" },
	    	"onloadstart":                    { type: "@event" },
	    	"onmousedown":                    { type: "@event" },
	    	"onmouseenter":                   { type: "@event" },
	    	"onmouseleave":                   { type: "@event" },
	    	"onmousemove":                    { type: "@event" },
	    	"onmouseout":                     { type: "@event" },
	    	"onmouseover":                    { type: "@event" },
	    	"onmouseup":                      { type: "@event" },
	    	"onmousewheel":                   { type: "@event" },
	    	"onpause":                        { type: "@event" },
	    	"onplay":                         { type: "@event" },
	    	"onplaying":                      { type: "@event" },
	    	"onprogress":                     { type: "@event" },
	    	"onratechange":                   { type: "@event" },
	    	"onreset":                        { type: "@event" },
	    	"onresize":                       { type: "@event" },
	    	"onscroll":                       { type: "@event" },
	    	"onseeked":                       { type: "@event" },
	    	"onseeking":                      { type: "@event" },
	    	"onselect":                       { type: "@event" },
	    	"onshow":                         { type: "@event" },
	    	"onstalled":                      { type: "@event" },
	    	"onsubmit":                       { type: "@event" },
	    	"onsuspend":                      { type: "@event" },
	    	"ontimeupdate":                   { type: "@event" },
	    	"ontoggle":                       { type: "@event" },
	    	"onvolumechange":                 { type: "@event" },
	    	"onwaiting":                      { type: "@event" },
	    	"style":						  { type: "CSSStyleDeclaration" },
	    	"tabIndex": 				      { type: "number" },
	    	"viewportElement":        		  { type: "Null", skipOpaque : true }
	    },
	    "Element": {
	        "animate":                        { type: "function" },
	        "attributes":                     { type: "NamedNodeMap" },
	        "childElementCount":              { type: "number", support: "@wip" },
	        "children":                       { type: "HTMLCollection" },
	        "classList":                      { type: "DOMTokenList" },
	        "className":                      { type: "string" },
	        "clientHeight":                   { type: "number" },
	        "clientLeft":                     { type: "number" },
	        "clientTop":                      { type: "number" },
	        "clientWidth":                    { type: "number" },
	        "closest":                        { type: "function" },
	        "createShadowRoot":               { type: "function", support: false },
	        "firstElementChild":              { type: "Null", support: "@wip" },
	        "getAttribute":                   { type: "function" },
	        "getAttributeNS":                 { type: "function" },
	        "getAttributeNode":               { type: "function" },
	        "getAttributeNodeNS":             { type: "function" },
	        "getBoundingClientRect":          { type: "function" },
	        "getClientRects":                 { type: "function" },
	        "getDestinationInsertionPoints":  { type: "function" },
	        "getElementsByClassName":         { type: "function" },
	        "getElementsByTagName":           { type: "function" },
	        "getElementsByTagNameNS":         { type: "function" },
	        "hasAttribute":                   { type: "function" },
	        "hasAttributeNS":                 { type: "function" },
	        "hasAttributes":                  { type: "function" },
	        "id":                             { type: "string" },
	        "innerHTML":                      { type: "string" },
	        "insertAdjacentElement":          { type: "function" },
	        "insertAdjacentHTML":             { type: "function" },
	        "insertAdjacentText":             { type: "function" },
	        "lastElementChild":               { type: "Null", support: "@wip" },
	        "localName":                      { type: "string" },
	        "matches":                        { type: "function" },
	        "namespaceURI":                   { type: "string" },
	        "nextElementSibling":             { type: "Null", skipOpaque : true },
	        "onbeforecopy":                   { type: "@event" },
	        "onbeforecut":                    { type: "@event" },
	        "onbeforepaste":                  { type: "@event" },
	        "oncopy":                         { type: "@event" },
	        "oncut":                          { type: "@event" },
	        "onpaste":                        { type: "@event" },
	        "onsearch":                       { type: "@event" },
	        "onselectstart":                  { type: "@event" },
	        "onwebkitfullscreenchange":       { type: "@event" },
	        "onwebkitfullscreenerror":        { type: "@event" },
	        "onwheel":                        { type: "@event" },
	        "outerHTML":                      { type: "string" },
	        "prefix":                         { type: "Null" },
	        "previousElementSibling":         { type: "Null", skipOpaque : true },
	        "querySelector":                  { type: "function" },
	        "querySelectorAll":               { type: "function" },
	        "remove":                         { type: "function" },
	        "removeAttribute":                { type: "function" },
	        "removeAttributeNS":              { type: "function" },
	        "removeAttributeNode":            { type: "function" },
	        "requestPointerLock":             { type: "function" },
	        "scrollHeight":                   { type: "number" },
	        "scrollIntoView":                 { type: "function" },
	        "scrollIntoViewIfNeeded":         { type: "function" },
	        "scrollLeft":                     { type: "number" },
	        "scrollTop":                      { type: "number" },
	        "scrollWidth":                    { type: "number" },
	        "setAttribute":                   { type: "function" },
	        "setAttributeNS":                 { type: "function" },
	        "setAttributeNode":               { type: "function" },
	        "setAttributeNodeNS":             { type: "function" },
	        "shadowRoot":                     { type: "Null", support: false },
	        "tagName":                        { type: "string" },
	        "webkitMatchesSelector":          { type: "function", support: false },
	        "webkitRequestFullScreen":        { type: "function", support: false },
	        "webkitRequestFullscreen":        { type: "function", support: false }
	    },
	    "Node": {
		    "ATTRIBUTE_NODE":                 { type: "number" },
		    "CDATA_SECTION_NODE":             { type: "number" },
		    "COMMENT_NODE":                   { type: "number" },
		    "DOCUMENT_FRAGMENT_NODE":         { type: "number" },
		    "DOCUMENT_NODE":                  { type: "number" },
		    "DOCUMENT_POSITION_CONTAINED_BY": { type: "number" },
		    "DOCUMENT_POSITION_CONTAINS":     { type: "number" },
		    "DOCUMENT_POSITION_DISCONNECTED": { type: "number" },
		    "DOCUMENT_POSITION_FOLLOWING":    { type: "number" },
		    "DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC":
		                                      { type: "number" },
		    "DOCUMENT_POSITION_PRECEDING":    { type: "number" },
		    "DOCUMENT_TYPE_NODE":             { type: "number" },
		    "ELEMENT_NODE":                   { type: "number" },
		    "ENTITY_NODE":                    { type: "number" },
		    "ENTITY_REFERENCE_NODE":          { type: "number" },
		    "NOTATION_NODE":                  { type: "number" },
		    "PROCESSING_INSTRUCTION_NODE":    { type: "number" },
		    "TEXT_NODE":                      { type: "number" },
		    "appendChild":                    { type: "function" },
		    "baseURI":                        { type: "string" },
		    "childNodes":                     { type: "NodeList" },
		    "cloneNode":                      { type: "function" },
		    "compareDocumentPosition":        { type: "function" },
		    "contains":                       { type: "function" },
		    "firstChild":                     { type: "Null", skipOpaque : true },
		    "hasChildNodes":                  { type: "function", support : "@wip" },
		    "insertBefore":                   { type: "function" },
		    "isConnected":                    { type: "boolean", support : false },
		    "isDefaultNamespace":             { type: "function", support : false },
		    "isEqualNode":                    { type: "function" },
		    "isSameNode":                     { type: "function" },
		    "lastChild":                      { type: "Null", skipOpaque : true },
		    "lookupNamespaceURI":             { type: "function" },
		    "lookupPrefix":                   { type: "function" },
		    "nextSibling":                    { type: "Null", skipOpaque : true },
		    "nodeName":                       { type: "string" },
		    "nodeType":                       { type: "number" },
		    "nodeValue":                      { type: "Null" },
		    "normalize":                      { type: "function" },
		    "ownerDocument":                  { type: "HTMLDocument" },
		    "parentElement":                  { type: "Null", skipOpaque : true },
		    "parentNode":                     { type: "Null", skipOpaque : true },
		    "previousSibling":                { type: "Null", skipOpaque : true },
		    "removeChild":                    { type: "function" },
		    "replaceChild":                   { type: "function" },
		    "textContent":                    { type: "string" },
		},
		"EventTarget": {
			"addEventListener":               { type: "function" },
		    "dispatchEvent":                  { type: "function" },
		    "removeEventListener":            { type: "function" }
		}
	}
})