/*
 * Copyright (C) 2013 salesforce.com, inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


/**
 * Construct a SecureWindow.
 *
 * @public
 * @class
 * @constructor
 *
 * @param {Object}
 *            win - the DOM window
 * @param {Object}
 *            key - the key to apply to the secure window
 */
function SecureWindow(win, key, globalAttributeWhitelist) {
	"use strict";

	var o = Object.create(null, {
		document: {
			enumerable: true,
			value: SecureDocument(win.document, key)
		},
		"$A": {
			enumerable: true,
			value: SecureAura(win['$A'], key)
		},
		window: {
			enumerable: true,
			get: function () {
				// circular window references to match DOM API
				return o;
			}
		},
		navigator: {
			enumerable: true,
			value: SecureNavigator(win.navigator, key)
		},
		XMLHttpRequest: {
			enumerable: true,
			value: SecureXMLHttpRequest(key)
		},
		setTimeout: {
			enumerable: true,
			value: function (callback) {
				return setTimeout.apply(win, [SecureObject.FunctionPrototypeBind.call(callback, o)].concat(SecureObject.ArrayPrototypeSlice.call(arguments, 1)));
			}
		},
		setInterval: {
			enumerable: true,
			value: function (callback) {
				return setInterval.apply(win, [SecureObject.FunctionPrototypeBind.call(callback, o)].concat(SecureObject.ArrayPrototypeSlice.call(arguments, 1)));
			}
		},
		toString: {
			value: function() {
				return "SecureWindow: " + win + "{ key: " + JSON.stringify(key) + " }";
			}
		}
	});

	[ "outerHeight", "outerWidth" ].forEach(function(name) {
		SecureObject.addPropertyIfSupported(o, win, name, {
			filterOpaque : true
		});
	});

	[ "getComputedStyle", "open", "scroll", "scrollBy", "scrollTo" ].forEach(function(name) {
		SecureObject.addMethodIfSupported(o, win, name, {
			filterOpaque : true
		});
	});

	SecureElement.addEventTargetMethods(o, win, key);

    // Salesforce API entry points (first phase) - W-3046191 is tracking adding $A.lockerService.publish() API enhancement where we will move these
    // to their respective javascript/container architectures
    ["sforce", "Sfdc"].forEach(function(name) {
		SecureObject.addPropertyIfSupported(o, win, name);
	});

	setLockerSecret(o, "key", key);
	setLockerSecret(o, "ref", win);

	// Has to happen last because it depends on the secure getters defined above that require the object to be keyed
	globalAttributeWhitelist.forEach(function(name) {
		// These are direct passthrough's and should never be wrapped in a SecureObject
		Object.defineProperty(o, name, {
			enumerable: true,
			value: win[name]
		});
	});

    SecureObject.addPrototypeMethodsAndProperties(SecureWindow.metadata, o, win, key);

	return o;
}

var DEFAULT = SecureElement.DEFAULT;
var FUNCTION = SecureElement.FUNCTION;
var EVENT = SecureElement.EVENT;
var CTOR = { type: "@ctor" };
var RAW = { type: "@raw" };

SecureWindow.metadata = {
	"prototypes": {
        "Window" : {
            "$A":                                   DEFAULT,
            "AnalyserNode":                         FUNCTION,
            "AnimationEvent":                       FUNCTION,
            "AppBannerPromptResult":                FUNCTION,
            "ApplicationCache":                     FUNCTION,
            "ApplicationCacheErrorEvent":           FUNCTION,
            "Array":                                RAW,
            "ArrayBuffer":                          RAW,
            "Attr":                                 RAW,
            "Audio":                                CTOR,
            "AudioBuffer":                          FUNCTION,
            "AudioBufferSourceNode":                FUNCTION,
            "AudioContext":                         FUNCTION,
            "AudioDestinationNode":                 FUNCTION,
            "AudioListener":                        FUNCTION,
            "AudioNode":                            FUNCTION,
            "AudioParam":                           FUNCTION,
            "AudioProcessingEvent":                 FUNCTION,
            "AutocompleteErrorEvent":               FUNCTION,
            "BarProp":                              FUNCTION,
            "BatteryManager":                       FUNCTION,
            "BeforeInstallPromptEvent":             FUNCTION,
            "BeforeUnloadEvent":                    FUNCTION,
            "BiquadFilterNode":                     FUNCTION,
            "BlobEvent":                            FUNCTION,
            "Boolean":                              FUNCTION,
            "CDATASection":                         FUNCTION,
            "CSS":                                  FUNCTION,
            "CSSFontFaceRule":                      FUNCTION,
            "CSSGroupingRule":                      FUNCTION,
            "CSSImportRule":                        FUNCTION,
            "CSSKeyframeRule":                      FUNCTION,
            "CSSKeyframesRule":                     FUNCTION,
            "CSSMediaRule":                         FUNCTION,
            "CSSNamespaceRule":                     FUNCTION,
            "CSSPageRule":                          FUNCTION,
            "CSSRule":                              FUNCTION,
            "CSSRuleList":                          FUNCTION,
            "CSSStyleDeclaration":                  FUNCTION,
            "CSSStyleRule":                         FUNCTION,
            "CSSStyleSheet":                        FUNCTION,
            "CSSSupportsRule":                      FUNCTION,
            "CSSViewportRule":                      FUNCTION,
            "CanvasCaptureMediaStreamTrack":        FUNCTION,
            "CanvasGradient":                       FUNCTION,
            "CanvasPattern":                        FUNCTION,
            "CanvasRenderingContext2D":             FUNCTION,
            "ChannelMergerNode":                    FUNCTION,
            "ChannelSplitterNode":                  FUNCTION,
            "CharacterData":                        FUNCTION,
            "ClientRect":                           FUNCTION,
            "ClientRectList":                       FUNCTION,
            "ClipboardEvent":                       FUNCTION,
            "CloseEvent":                           FUNCTION,
            "Comment":                              FUNCTION,
            "CompositionEvent":                     FUNCTION,
            "ConvolverNode":                        FUNCTION,
            "Credential":                           FUNCTION,
            "CredentialsContainer":                 FUNCTION,
            "Crypto":                               FUNCTION,
            "CryptoKey":                            FUNCTION,
            "CustomEvent":                          FUNCTION,
            "DOMError":                             FUNCTION,
            "DOMException":                         FUNCTION,
            "DOMImplementation":                    FUNCTION,
            "DOMParser":                            FUNCTION,
            "DOMStringList":                        FUNCTION,
            "DOMStringMap":                         FUNCTION,
            "DOMTokenList":                         FUNCTION,
            "DataTransfer":                         FUNCTION,
            "DataTransferItem":                     FUNCTION,
            "DataTransferItemList":                 FUNCTION,
            "DataView":                             FUNCTION,
            "Date":                                 FUNCTION,
            "DelayNode":                            FUNCTION,
            "DeviceMotionEvent":                    FUNCTION,
            "DeviceOrientationEvent":               FUNCTION,
            "Document":                             FUNCTION,
            "DocumentFragment":                     FUNCTION,
            "DocumentType":                         FUNCTION,
            "DragEvent":                            FUNCTION,
            "DynamicsCompressorNode":               FUNCTION,
            "ES6Promise":                           DEFAULT,
            "Element":                              FUNCTION,
            "Error":                                FUNCTION,
            "ErrorEvent":                           FUNCTION,
            "EvalError":                            FUNCTION,
            "Event":                                FUNCTION,
            "EventSource":                          FUNCTION,
            "EventTarget":                          FUNCTION,
            "FederatedCredential":                  FUNCTION,
            "File":                                 FUNCTION,
            "FileError":                            FUNCTION,
            "FileList":                             FUNCTION,
            "FileReader":                           FUNCTION,
            "Float32Array":                         FUNCTION,
            "Float64Array":                         FUNCTION,
            "FocusEvent":                           FUNCTION,
            "FontFace":                             FUNCTION,
            "FormData":                             FUNCTION,
            "Function":                             FUNCTION,
            "GainNode":                             FUNCTION,
            "HTMLAllCollection":                    FUNCTION,
            "HTMLAnchorElement":                    CTOR,
            "HTMLAreaElement":                      CTOR,
            "HTMLAudioElement":                     CTOR,
            "HTMLBRElement":                        CTOR,
            "HTMLBaseElement":                      CTOR,
            "HTMLBodyElement":                      CTOR,
            "HTMLButtonElement":                    CTOR,
            "HTMLCanvasElement":                    CTOR,
            "HTMLCollection":                       CTOR,
            "HTMLContentElement":                   CTOR,
            "HTMLDListElement":                     CTOR,
            "HTMLDataListElement":                  CTOR,
            "HTMLDetailsElement":                   CTOR,
            "HTMLDialogElement":                    CTOR,
            "HTMLDireCTORyElement":                 CTOR,
            "HTMLDivElement":                       CTOR,
            "HTMLDocument":                         CTOR,
            "HTMLElement":                          CTOR,
            "HTMLEmbedElement":                     CTOR,
            "HTMLFieldSetElement":                  CTOR,
            "HTMLFontElement":                      CTOR,
            "HTMLFormControlsCollection":           FUNCTION,
            "HTMLFormElement":                      CTOR,
            "HTMLFrameElement":                     CTOR,
            "HTMLFrameSetElement":                  CTOR,
            "HTMLHRElement":                        CTOR,
            "HTMLHeadElement":                      CTOR,
            "HTMLHeadingElement":                   CTOR,
            "HTMLHtmlElement":                      CTOR,
            "HTMLIFrameElement":                    CTOR,
            "HTMLImageElement":                     CTOR,
            "HTMLInputElement":                     CTOR,
            "HTMLKeygenElement":                    CTOR,
            "HTMLLIElement":                        CTOR,
            "HTMLLabelElement":                     CTOR,
            "HTMLLegendElement":                    CTOR,
            "HTMLLinkElement":                      CTOR,
            "HTMLMapElement":                       CTOR,
            "HTMLMarqueeElement":                   CTOR,
            "HTMLMediaElement":                     CTOR,
            "HTMLMenuElement":                      CTOR,
            "HTMLMetaElement":                      CTOR,
            "HTMLMeterElement":                     CTOR,
            "HTMLModElement":                       CTOR,
            "HTMLOListElement":                     CTOR,
            "HTMLObjectElement":                    CTOR,
            "HTMLOptGroupElement":                  CTOR,
            "HTMLOptionElement":                    CTOR,
            "HTMLOptionsCollection":                CTOR,
            "HTMLOutputElement":                    CTOR,
            "HTMLParagraphElement":                 CTOR,
            "HTMLParamElement":                     CTOR,
            "HTMLPictureElement":                   CTOR,
            "HTMLPreElement":                       CTOR,
            "HTMLProgressElement":                  CTOR,
            "HTMLQuoteElement":                     CTOR,
            "HTMLScriptElement":                    CTOR,
            "HTMLSelectElement":                    CTOR,
            "HTMLShadowElement":                    CTOR,
            "HTMLSourceElement":                    CTOR,
            "HTMLSpanElement":                      CTOR,
            "HTMLStyleElement":                     CTOR,
            "HTMLTableCaptionElement":              CTOR,
            "HTMLTableCellElement":                 CTOR,
            "HTMLTableColElement":                  CTOR,
            "HTMLTableElement":                     CTOR,
            "HTMLTableRowElement":                  CTOR,
            "HTMLTableSectionElement":              CTOR,
            "HTMLTemplateElement":                  CTOR,
            "HTMLTextAreaElement":                  CTOR,
            "HTMLTitleElement":                     CTOR,
            "HTMLTrackElement":                     CTOR,
            "HTMLUListElement":                     CTOR,
            "HTMLUnknownElement":                   CTOR,
            "HTMLVideoElement":                     CTOR,
            "HashChangeEvent":                      FUNCTION,
            "IdleDeadline":                         FUNCTION,
            "Image":                                FUNCTION,
            "ImageBitmap":                          FUNCTION,
            "ImageData":                            FUNCTION,
            "Infinity":                             DEFAULT,
            "InputDeviceCapabilities":              FUNCTION,
            "Int16Array":                           FUNCTION,
            "Int32Array":                           FUNCTION,
            "Int8Array":                            FUNCTION,
            "Intl":                                 DEFAULT,
            "JSON":                                 DEFAULT,
            "KeyboardEvent":                        FUNCTION,
            "Location":                             FUNCTION,
            "MIDIAccess":                           FUNCTION,
            "MIDIConnectionEvent":                  FUNCTION,
            "MIDIInput":                            FUNCTION,
            "MIDIInputMap":                         FUNCTION,
            "MIDIMessageEvent":                     FUNCTION,
            "MIDIOutput":                           FUNCTION,
            "MIDIOutputMap":                        FUNCTION,
            "MIDIPort":                             FUNCTION,
            "Map":                                  RAW,
            "Math":                                 DEFAULT,
            "MediaDevices":                         FUNCTION,
            "MediaElementAudioSourceNode":          FUNCTION,
            "MediaEncryptedEvent":                  FUNCTION,
            "MediaError":                           FUNCTION,
            "MediaKeyMessageEvent":                 FUNCTION,
            "MediaKeySession":                      FUNCTION,
            "MediaKeyStatusMap":                    FUNCTION,
            "MediaKeySystemAccess":                 FUNCTION,
            "MediaKeys":                            FUNCTION,
            "MediaList":                            FUNCTION,
            "MediaQueryList":                       FUNCTION,
            "MediaQueryListEvent":                  FUNCTION,
            "MediaRecorder":                        FUNCTION,
            "MediaSource":                          FUNCTION,
            "MediaStreamAudioDestinationNode":      FUNCTION,
            "MediaStreamAudioSourceNode":           FUNCTION,
            "MediaStreamEvent":                     FUNCTION,
            "MediaStreamTrack":                     FUNCTION,
            "MessageChannel":                       FUNCTION,
            "MessageEvent":                         FUNCTION,
            "MessagePort":                          FUNCTION,
            "MimeType":                             FUNCTION,
            "MimeTypeArray":                        FUNCTION,
            "MouseEvent":                           FUNCTION,
            "NaN":                                  DEFAULT,
            "NamedNodeMap":                         FUNCTION,
            "Navigator":                            FUNCTION,
            "Node":                                 FUNCTION,
            "NodeFilter":                           FUNCTION,
            "NodeIterator":                         FUNCTION,
            "NodeList":                             FUNCTION,
            "Notification":                         FUNCTION,
            "Number":                               FUNCTION,
            "Object":                               FUNCTION,
            "OfflineAudioCompletionEvent":          FUNCTION,
            "OfflineAudioContext":                  FUNCTION,
            "Option":                               FUNCTION,
            "OscillatorNode":                       FUNCTION,
            "PERSISTENT":                           DEFAULT,
            "PageTransitionEvent":                  FUNCTION,
            "PasswordCredential":                   FUNCTION,
            "Path2D":                               FUNCTION,
            "Performance":                          FUNCTION,
            "PerformanceEntry":                     FUNCTION,
            "PerformanceMark":                      FUNCTION,
            "PerformanceMeasure":                   FUNCTION,
            "PerformanceNavigation":                FUNCTION,
            "PerformanceResourceTiming":            FUNCTION,
            "PerformanceTiming":                    FUNCTION,
            "PeriodicWave":                         FUNCTION,
            "PopStateEvent":                        FUNCTION,
            "Presentation":                         FUNCTION,
            "PresentationAvailability":             FUNCTION,
            "PresentationConnection":               FUNCTION,
            "PresentationConnectionAvailableEvent": FUNCTION,
            "PresentationConnectionCloseEvent":     FUNCTION,
            "PresentationRequest":                  FUNCTION,
            "ProcessingInstruction":                FUNCTION,
            "ProgressEvent":                        FUNCTION,
            "Promise":                              FUNCTION,
            "PromiseRejectionEvent":                FUNCTION,
            "RTCCertificate":                       FUNCTION,
            "RTCIceCandidate":                      FUNCTION,
            "RTCSessionDescription":                FUNCTION,
            "RadioNodeList":                        FUNCTION,
            "Range":                                FUNCTION,
            "RangeError":                           FUNCTION,
            "ReadableByteStream":                   FUNCTION,
            "ReadableStream":                       FUNCTION,
            "ReferenceError":                       FUNCTION,
            "Reflect":                              DEFAULT,
            "RegExp":                               FUNCTION,
            "Request":                              FUNCTION,
            "Response":                             FUNCTION,
            "SVGAElement":                          FUNCTION,
            "SVGAngle":                             FUNCTION,
            "SVGAnimateElement":                    FUNCTION,
            "SVGAnimateMotionElement":              FUNCTION,
            "SVGAnimateTransformElement":           FUNCTION,
            "SVGAnimatedAngle":                     FUNCTION,
            "SVGAnimatedBoolean":                   FUNCTION,
            "SVGAnimatedEnumeration":               FUNCTION,
            "SVGAnimatedInteger":                   FUNCTION,
            "SVGAnimatedLength":                    FUNCTION,
            "SVGAnimatedLengthList":                FUNCTION,
            "SVGAnimatedNumber":                    FUNCTION,
            "SVGAnimatedNumberList":                FUNCTION,
            "SVGAnimatedPreserveAspectRatio":       FUNCTION,
            "SVGAnimatedRect":                      FUNCTION,
            "SVGAnimatedString":                    FUNCTION,
            "SVGAnimatedTransformList":             FUNCTION,
            "SVGAnimationElement":                  CTOR,
            "SVGCircleElement":                     CTOR,
            "SVGClipPathElement":                   CTOR,
            "SVGComponentTransferFunctionElement":  CTOR,
            "SVGCursorElement":                     CTOR,
            "SVGDefsElement":                       CTOR,
            "SVGDescElement":                       CTOR,
            "SVGDiscardElement":                    CTOR,
            "SVGElement":                           CTOR,
            "SVGEllipseElement":                    CTOR,
            "SVGFEBlendElement":                    CTOR,
            "SVGFEColorMatrixElement":              CTOR,
            "SVGFEComponentTransferElement":        CTOR,
            "SVGFECompositeElement":                CTOR,
            "SVGFEConvolveMatrixElement":           CTOR,
            "SVGFEDiffuseLightingElement":          CTOR,
            "SVGFEDisplacementMapElement":          CTOR,
            "SVGFEDistantLightElement":             CTOR,
            "SVGFEDropShadowElement":               CTOR,
            "SVGFEFloodElement":                    CTOR,
            "SVGFEFuncAElement":                    CTOR,
            "SVGFEFuncBElement":                    CTOR,
            "SVGFEFuncGElement":                    CTOR,
            "SVGFEFuncRElement":                    CTOR,
            "SVGFEGaussianBlurElement":             CTOR,
            "SVGFEImageElement":                    CTOR,
            "SVGFEMergeElement":                    CTOR,
            "SVGFEMergeNodeElement":                CTOR,
            "SVGFEMorphologyElement":               CTOR,
            "SVGFEOffsetElement":                   CTOR,
            "SVGFEPointLightElement":               CTOR,
            "SVGFESpecularLightingElement":         CTOR,
            "SVGFESpotLightElement":                CTOR,
            "SVGFETileElement":                     CTOR,
            "SVGFETurbulenceElement":               CTOR,
            "SVGFilterElement":                     CTOR,
            "SVGForeignObjectElement":              CTOR,
            "SVGGElement":                          CTOR,
            "SVGGeometryElement":                   CTOR,
            "SVGGradientElement":                   CTOR,
            "SVGGraphicsElement":                   CTOR,
            "SVGImageElement":                      CTOR,
            "SVGLength":                            FUNCTION,
            "SVGLengthList":                        FUNCTION,
            "SVGLineElement":                       CTOR,
            "SVGLinearGradientElement":             CTOR,
            "SVGMPathElement":                      CTOR,
            "SVGMarkerElement":                     CTOR,
            "SVGMaskElement":                       CTOR,
            "SVGMatrix":                            CTOR,
            "SVGMetadataElement":                   CTOR,
            "SVGNumber":                            FUNCTION,
            "SVGNumberList":                        FUNCTION,
            "SVGPathElement":                       CTOR,
            "SVGPatternElement":                    CTOR,
            "SVGPoint":                             FUNCTION,
            "SVGPointList":                         FUNCTION,
            "SVGPolygonElement":                    CTOR,
            "SVGPolylineElement":                   CTOR,
            "SVGPreserveAspectRatio":               FUNCTION,
            "SVGRadialGradientElement":             CTOR,
            "SVGRect":                              FUNCTION,
            "SVGRectElement":                       CTOR,
            "SVGSVGElement":                        CTOR,
            "SVGScriptElement":                     CTOR,
            "SVGSetElement":                        CTOR,
            "SVGStopElement":                       CTOR,
            "SVGStringList":                        FUNCTION,
            "SVGStyleElement":                      CTOR,
            "SVGSwitchElement":                     CTOR,
            "SVGSymbolElement":                     CTOR,
            "SVGTSpanElement":                      CTOR,
            "SVGTextContentElement":                CTOR,
            "SVGTextElement":                       CTOR,
            "SVGTextPathElement":                   CTOR,
            "SVGTextPositioningElement":            CTOR,
            "SVGTitleElement":                      CTOR,
            "SVGTransform":                         FUNCTION,
            "SVGTransformList":                     FUNCTION,
            "SVGUnitTypes":                         FUNCTION,
            "SVGUseElement":                        CTOR,
            "SVGViewElement":                       CTOR,
            "SVGViewSpec":                          FUNCTION,
            "SVGZoomEvent":                         FUNCTION,
            "Screen":                               FUNCTION,
            "ScreenOrientation":                    FUNCTION,
            "SecurityPolicyViolationEvent":         FUNCTION,
            "Selection":                            FUNCTION,
            "Set":                                  RAW,
            "SourceBuffer":                         FUNCTION,
            "SourceBufferList":                     FUNCTION,
            "SpeechSynthesisEvent":                 FUNCTION,
            "SpeechSynthesisUtterance":             FUNCTION,
            "String":                               FUNCTION,
            "StyleSheet":                           FUNCTION,
            "StyleSheetList":                       FUNCTION,
            "SubtleCrypto":                         FUNCTION,
            "Symbol":                               FUNCTION,
            "SyntaxError":                          FUNCTION,
            "TEMPORARY":                            DEFAULT,
            "Text":                                 FUNCTION,
            "TextDecoder":                          FUNCTION,
            "TextEncoder":                          FUNCTION,
            "TextEvent":                            FUNCTION,
            "TextMetrics":                          FUNCTION,
            "TextTrack":                            FUNCTION,
            "TextTrackCue":                         FUNCTION,
            "TextTrackCueList":                     FUNCTION,
            "TextTrackList":                        FUNCTION,
            "TimeRanges":                           FUNCTION,
            "Touch":                                FUNCTION,
            "TouchEvent":                           FUNCTION,
            "TouchList":                            FUNCTION,
            "TrackEvent":                           FUNCTION,
            "TransitionEvent":                      FUNCTION,
            "TreeWalker":                           FUNCTION,
            "TypeError":                            FUNCTION,
            "UIEvent":                              FUNCTION,
            "URIError":                             FUNCTION,
            "URL":                                  FUNCTION,
            "URLSearchParams":                      FUNCTION,
            "Uint16Array":                          FUNCTION,
            "Uint32Array":                          FUNCTION,
            "Uint8Array":                           FUNCTION,
            "Uint8ClampedArray":                    FUNCTION,
            "VTTCue":                               FUNCTION,
            "ValidityState":                        FUNCTION,
            "WaveShaperNode":                       FUNCTION,
            "WeakMap":                              RAW,
            "WeakSet":                              RAW,
            "WebGLActiveInfo":                      FUNCTION,
            "WebGLBuffer":                          FUNCTION,
            "WebGLContextEvent":                    FUNCTION,
            "WebGLFramebuffer":                     FUNCTION,
            "WebGLProgram":                         FUNCTION,
            "WebGLRenderbuffer":                    FUNCTION,
            "WebGLRenderingContext":                FUNCTION,
            "WebGLShader":                          FUNCTION,
            "WebGLShaderPrecisionFormat":           FUNCTION,
            "WebGLTexture":                         FUNCTION,
            "WebGLUniformLocation":                 FUNCTION,
            "WebKitAnimationEvent":                 FUNCTION,
            "WebKitCSSMatrix":                      FUNCTION,
            "WebKitMutationObserver":               FUNCTION,
            "WebKitTransitionEvent":                FUNCTION,
            "WebSocket":                            FUNCTION,
            "WheelEvent":                           FUNCTION,
            "Window":                               FUNCTION,
            "XMLDocument":                          FUNCTION,
            "XMLHttpRequest":                       FUNCTION,
            "XMLHttpRequestEventTarget":            FUNCTION,
            "XMLHttpRequestUpload":                 FUNCTION,
            "XMLSerializer":                        FUNCTION,
            "XPathEvaluator":                       FUNCTION,
            "XPathExpression":                      FUNCTION,
            "XPathResult":                          FUNCTION,
            "XSLTProcessor":                        FUNCTION,
            "alert":                                FUNCTION,
            "atob":                                 FUNCTION,
            "aura":                                 DEFAULT,
            "blur":                                 FUNCTION,
            "btoa":                                 FUNCTION,
            "cancelAnimationFrame":                 FUNCTION,
            "cancelIdleCallback":                   FUNCTION,
            "captureEvents":                        FUNCTION,
            "chrome":                               DEFAULT,
            "clearInterval":                        FUNCTION,
            "clearTimeout":                         FUNCTION,
            "close":                                FUNCTION,
            "closed":                               DEFAULT,
            "confirm":                              FUNCTION,
            "console":                              DEFAULT,
            "createImageBitmap":                    FUNCTION,
            "crypto":                               DEFAULT,
            "decodeURI":                            FUNCTION,
            "decodeURIComponent":                   FUNCTION,
            "defaultStatus":                        DEFAULT,
            "defaultstatus":                        DEFAULT,
            "devicePixelRatio":                     DEFAULT,
            "document":                             DEFAULT,
            "encodeURI":                            FUNCTION,
            "encodeURIComponent":                   FUNCTION,
            "escape":                               FUNCTION,
            "external":                             DEFAULT,
            "fetch":                                FUNCTION,
            "find":                                 FUNCTION,
            "focus":                                FUNCTION,
            "frameElement":                         DEFAULT,
            "frames":                               DEFAULT,
            "getComputedStyle":                     FUNCTION,
            "getMatchedCSSRules":                   FUNCTION,
            "getSelection":                         FUNCTION,
            "history":                              DEFAULT,
            "innerHeight":                          DEFAULT,
            "innerWidth":                           DEFAULT,
            "isFinite":                             FUNCTION,
            "isNaN":                                FUNCTION,
            "isSecureContext":                      DEFAULT,
            "length":                               DEFAULT,
            "location":                             DEFAULT,
            "locationbar":                          DEFAULT,
            "matchMedia":                           FUNCTION,
            "menubar":                              DEFAULT,
            "moment":                               FUNCTION,
            "moveBy":                               FUNCTION,
            "moveTo":                               FUNCTION,
            "name":                                 DEFAULT,
            "navigator":                            DEFAULT,
            "offscreenBuffering":                   DEFAULT,
            "onabort":                              EVENT,
            "onanimationend":                       EVENT,
            "onanimationiteration":                 EVENT,
            "onanimationstart":                     EVENT,
            "onautocomplete":                       EVENT,
            "onautocompleteerror":                  EVENT,
            "onbeforeunload":                       EVENT,
            "onblur":                               EVENT,
            "oncancel":                             EVENT,
            "oncanplay":                            EVENT,
            "oncanplaythrough":                     EVENT,
            "onchange":                             EVENT,
            "onclick":                              EVENT,
            "onclose":                              EVENT,
            "oncontextmenu":                        EVENT,
            "oncuechange":                          EVENT,
            "ondblclick":                           EVENT,
            "ondevicemotion":                       EVENT,
            "ondeviceorientation":                  EVENT,
            "ondeviceorientationabsolute":          EVENT,
            "ondrag":                               EVENT,
            "ondragend":                            EVENT,
            "ondragenter":                          EVENT,
            "ondragleave":                          EVENT,
            "ondragover":                           EVENT,
            "ondragstart":                          EVENT,
            "ondrop":                               EVENT,
            "ondurationchange":                     EVENT,
            "onemptied":                            EVENT,
            "onended":                              EVENT,
            "onerror":                              FUNCTION,
            "onfocus":                              EVENT,
            "onhashchange":                         EVENT,
            "oninput":                              EVENT,
            "oninvalid":                            EVENT,
            "onkeydown":                            EVENT,
            "onkeypress":                           EVENT,
            "onkeyup":                              EVENT,
            "onlanguagechange":                     EVENT,
            "onload":                               EVENT,
            "onloadeddata":                         EVENT,
            "onloadedmetadata":                     EVENT,
            "onloadstart":                          EVENT,
            "onmessage":                            EVENT,
            "onmousedown":                          EVENT,
            "onmouseenter":                         EVENT,
            "onmouseleave":                         EVENT,
            "onmousemove":                          EVENT,
            "onmouseout":                           EVENT,
            "onmouseover":                          EVENT,
            "onmouseup":                            EVENT,
            "onmousewheel":                         EVENT,
            "onoffline":                            EVENT,
            "ononline":                             EVENT,
            "onpagehide":                           EVENT,
            "onpageshow":                           EVENT,
            "onpause":                              EVENT,
            "onplay":                               EVENT,
            "onplaying":                            EVENT,
            "onpopstate":                           EVENT,
            "onprogress":                           EVENT,
            "onratechange":                         EVENT,
            "onrejectionhandled":                   EVENT,
            "onreset":                              EVENT,
            "onresize":                             EVENT,
            "onscroll":                             EVENT,
            "onsearch":                             EVENT,
            "onseeked":                             EVENT,
            "onseeking":                            EVENT,
            "onselect":                             EVENT,
            "onshow":                               EVENT,
            "onstalled":                            EVENT,
            "onstorage":                            EVENT,
            "onsubmit":                             EVENT,
            "onsuspend":                            EVENT,
            "ontimeupdate":                         EVENT,
            "ontoggle":                             EVENT,
            "ontransitionend":                      EVENT,
	        "ontouchcancel":               	  		EVENT,
	        "ontouchend":                	  		EVENT,
	        "ontouchmove":                	  		EVENT,
	        "ontouchstart":                	  		EVENT,
            "onunhandledrejection":                 EVENT,
            "onunload":                             EVENT,
            "onvolumechange":                       EVENT,
            "onwaiting":                            EVENT,
            "onwheel":                              EVENT,
            "open":                                 FUNCTION,
            "outerHeight":                          DEFAULT,
            "outerWidth":                           DEFAULT,
            "pageStartTime":                        DEFAULT,
            "pageXOffset":                          DEFAULT,
            "pageYOffset":                          DEFAULT,
            "parseFloat":                           FUNCTION,
            "parseInt":                             FUNCTION,
            "performance":                          DEFAULT,
            "personalbar":                          DEFAULT,
            "postMessage":                          FUNCTION,
            "print":                                FUNCTION,
            "prompt":                               FUNCTION,
            "releaseEvents":                        FUNCTION,
            "requestAnimationFrame":                FUNCTION,
            "requestIdleCallback":                  FUNCTION,
            "resizeBy":                             FUNCTION,
            "resizeTo":                             FUNCTION,
            "screen":                               DEFAULT,
            "screenLeft":                           DEFAULT,
            "screenTop":                            DEFAULT,
            "screenX":                              DEFAULT,
            "screenY":                              DEFAULT,
            "scroll":                               FUNCTION,
            "scrollBy":                             FUNCTION,
            "scrollTo":                             FUNCTION,
            "scrollX":                              DEFAULT,
            "scrollY":                              DEFAULT,
            "scrollbars":                           DEFAULT,
            "self":                                 DEFAULT,
            "setInterval":                          FUNCTION,
            "setTimeout":                           FUNCTION,
            "status":                               DEFAULT,
            "statusbar":                            DEFAULT,
            "stop":                                 FUNCTION,
            "styleMedia":                           DEFAULT,
            "toolbar":                              DEFAULT,
            "undefined":                            DEFAULT,
            "unescape":                             FUNCTION,
            "window":                               DEFAULT
        },
        "EventTarget": SecureElement.eventTargetMetadata
    }
};