({
    testName: {
        "systemAPI": "Window",
        "secureAPI": "SecureWindow"
    },
    testPlan: {
        "Window" : {
            "$$safe-eval$$":                        { type: "function", support: false  },
            "$$safe-eval-compat$$":                 { type: "function", support: false  },
            "$A":                                   { type: "Object" },
            "AnalyserNode":                         { type: "function" },
            "AnimationEvent":                       { type: "function" },
            "AppBannerPromptResult":                { type: "function" },
            "ApplicationCache":                     { type: "function" },
            "ApplicationCacheErrorEvent":           { type: "function" },
            "Array":                                { type: "function" },
            "ArrayBuffer":                          { type: "function" },
            "Attr":                                 { type: "function" },
            "Audio":                                { type: "function", support: "202" },
            "AudioBuffer":                          { type: "function" },
            "AudioBufferSourceNode":                { type: "function" },
            "AudioContext":                         { type: "function" },
            "AudioDestinationNode":                 { type: "function" },
            "AudioListener":                        { type: "function" },
            "AudioNode":                            { type: "function" },
            "AudioParam":                           { type: "function" },
            "AudioProcessingEvent":                 { type: "function" },
            "Aura":                                 { type: "Object", support: false },
            "AutocompleteErrorEvent":               { type: "function" },
            "BarProp":                              { type: "function" },
            "BatteryManager":                       { type: "function" },
            "BeforeInstallPromptEvent":             { type: "function" },
            "BeforeUnloadEvent":                    { type: "function" },
            "BiquadFilterNode":                     { type: "function" },
            "Blob":                                 { type: "function", support: "@wip" },
            "BlobEvent":                            { type: "function" },
            "Boolean":                              { type: "function" },
            "CDATASection":                         { type: "function" },
            "CSS":                                  { type: "function" },
            "CSSFontFaceRule":                      { type: "function" },
            "CSSGroupingRule":                      { type: "function" },
            "CSSImportRule":                        { type: "function" },
            "CSSKeyframeRule":                      { type: "function" },
            "CSSKeyframesRule":                     { type: "function" },
            "CSSMediaRule":                         { type: "function" },
            "CSSNamespaceRule":                     { type: "function" },
            "CSSPageRule":                          { type: "function" },
            "CSSRule":                              { type: "function" },
            "CSSRuleList":                          { type: "function" },
            "CSSStyleDeclaration":                  { type: "function" },
            "CSSStyleRule":                         { type: "function" },
            "CSSStyleSheet":                        { type: "function" },
            "CSSSupportsRule":                      { type: "function" },
            "CSSViewportRule":                      { type: "function" },
            "Cache":                                { type: "function", support: "@wip" },
            "CacheStorage":                         { type: "function", support: "@wip" },
            "CanvasCaptureMediaStreamTrack":        { type: "function" },
            "CanvasGradient":                       { type: "function" },
            "CanvasPattern":                        { type: "function" },
            "CanvasRenderingContext2D":             { type: "function" },
            "ChannelMergerNode":                    { type: "function" },
            "ChannelSplitterNode":                  { type: "function" },
            "CharacterData":                        { type: "function" },
            "ClientRect":                           { type: "function" },
            "ClientRectList":                       { type: "function" },
            "ClipboardEvent":                       { type: "function" },
            "CloseEvent":                           { type: "function" },
            "Comment":                              { type: "function" },
            "CompositionEvent":                     { type: "function" },
            "ConvolverNode":                        { type: "function" },
            "Credential":                           { type: "function" },
            "CredentialsContainer":                 { type: "function" },
            "Crypto":                               { type: "function" },
            "CryptoKey":                            { type: "function" },
            "CustomEvent":                          { type: "function" },
            "DOMError":                             { type: "function" },
            "DOMException":                         { type: "function" },
            "DOMImplementation":                    { type: "function" },
            "DOMParser":                            { type: "function" },
            "DOMPurify":                            { type: "function", support: false },
            "DOMStringList":                        { type: "function" },
            "DOMStringMap":                         { type: "function" },
            "DOMTokenList":                         { type: "function" },
            "DataTransfer":                         { type: "function" },
            "DataTransferItem":                     { type: "function" },
            "DataTransferItemList":                 { type: "function" },
            "DataView":                             { type: "function" },
            "Date":                                 { type: "function" },
            "DelayNode":                            { type: "function" },
            "DeviceMotionEvent":                    { type: "function" },
            "DeviceOrientationEvent":               { type: "function" },
            "Document":                             { type: "function" },
            "DocumentFragment":                     { type: "function" },
            "DocumentType":                         { type: "function" },
            "DragEvent":                            { type: "function" },
            "DynamicsCompressorNode":               { type: "function" },
            "ES6Promise":                           { type: "Object" },
            "Element":                              { type: "function" },
            "Error":                                { type: "function" },
            "ErrorEvent":                           { type: "function" },
            "EvalError":                            { type: "function" },
            "Event":                                { type: "function" },
            "EventSource":                          { type: "function" },
            "EventTarget":                          { type: "function" },
            "FastClick":                            { type: "function", support: false },
            "FederatedCredential":                  { type: "function" },
            "File":                                 { type: "function" },
            "FileError":                            { type: "function" },
            "FileList":                             { type: "function" },
            "FileReader":                           { type: "function" },
            "Float32Array":                         { type: "function" },
            "Float64Array":                         { type: "function" },
            "FocusEvent":                           { type: "function" },
            "FontFace":                             { type: "function" },
            "FormData":                             { type: "function" },
            "Function":                             { type: "function" },
            "GainNode":                             { type: "function" },
            "Gamepad":                              { type: "function", support: "@wip" },
            "GamepadButton":                        { type: "function", support: "@wip" },
            "GamepadEvent":                         { type: "function", support: "@wip" },
            "HTMLAllCollection":                    { type: "function" },
            "HTMLAnchorElement":                    { type: "function" },
            "HTMLAreaElement":                      { type: "function" },
            "HTMLAudioElement":                     { type: "function" },
            "HTMLBRElement":                        { type: "function" },
            "HTMLBaseElement":                      { type: "function" },
            "HTMLBodyElement":                      { type: "function" },
            "HTMLButtonElement":                    { type: "function" },
            "HTMLCanvasElement":                    { type: "function" },
            "HTMLCollection":                       { type: "function" },
            "HTMLContentElement":                   { type: "function" },
            "HTMLDListElement":                     { type: "function" },
            "HTMLDataListElement":                  { type: "function" },
            "HTMLDetailsElement":                   { type: "function" },
            "HTMLDialogElement":                    { type: "function" },
            "HTMLDirectoryElement":                 { type: "function", support: false },
            "HTMLDivElement":                       { type: "function" },
            "HTMLDocument":                         { type: "function" },
            "HTMLElement":                          { type: "function" },
            "HTMLEmbedElement":                     { type: "function" },
            "HTMLFieldSetElement":                  { type: "function" },
            "HTMLFontElement":                      { type: "function" },
            "HTMLFormControlsCollection":           { type: "function" },
            "HTMLFormElement":                      { type: "function" },
            "HTMLFrameElement":                     { type: "function" },
            "HTMLFrameSetElement":                  { type: "function" },
            "HTMLHRElement":                        { type: "function" },
            "HTMLHeadElement":                      { type: "function" },
            "HTMLHeadingElement":                   { type: "function" },
            "HTMLHtmlElement":                      { type: "function" },
            "HTMLIFrameElement":                    { type: "function" },
            "HTMLImageElement":                     { type: "function" },
            "HTMLInputElement":                     { type: "function" },
            "HTMLKeygenElement":                    { type: "function" },
            "HTMLLIElement":                        { type: "function" },
            "HTMLLabelElement":                     { type: "function" },
            "HTMLLegendElement":                    { type: "function" },
            "HTMLLinkElement":                      { type: "function" },
            "HTMLMapElement":                       { type: "function" },
            "HTMLMarqueeElement":                   { type: "function" },
            "HTMLMediaElement":                     { type: "function" },
            "HTMLMenuElement":                      { type: "function" },
            "HTMLMetaElement":                      { type: "function" },
            "HTMLMeterElement":                     { type: "function" },
            "HTMLModElement":                       { type: "function" },
            "HTMLOListElement":                     { type: "function" },
            "HTMLObjectElement":                    { type: "function" },
            "HTMLOptGroupElement":                  { type: "function" },
            "HTMLOptionElement":                    { type: "function" },
            "HTMLOptionsCollection":                { type: "function" },
            "HTMLOutputElement":                    { type: "function" },
            "HTMLParagraphElement":                 { type: "function" },
            "HTMLParamElement":                     { type: "function" },
            "HTMLPictureElement":                   { type: "function" },
            "HTMLPreElement":                       { type: "function" },
            "HTMLProgressElement":                  { type: "function" },
            "HTMLQuoteElement":                     { type: "function" },
            "HTMLScriptElement":                    { type: "function" },
            "HTMLSelectElement":                    { type: "function" },
            "HTMLShadowElement":                    { type: "function" },
            "HTMLSourceElement":                    { type: "function" },
            "HTMLSpanElement":                      { type: "function" },
            "HTMLStyleElement":                     { type: "function" },
            "HTMLTableCaptionElement":              { type: "function" },
            "HTMLTableCellElement":                 { type: "function" },
            "HTMLTableColElement":                  { type: "function" },
            "HTMLTableElement":                     { type: "function" },
            "HTMLTableRowElement":                  { type: "function" },
            "HTMLTableSectionElement":              { type: "function" },
            "HTMLTemplateElement":                  { type: "function" },
            "HTMLTextAreaElement":                  { type: "function" },
            "HTMLTitleElement":                     { type: "function" },
            "HTMLTrackElement":                     { type: "function" },
            "HTMLUListElement":                     { type: "function" },
            "HTMLUnknownElement":                   { type: "function" },
            "HTMLVideoElement":                     { type: "function" },
            "HashChangeEvent":                      { type: "function" },
            "Headers":                              { type: "function", support: "@wip" },
            "History":                              { type: "function", support: "@wip" },
            "IDBCursor":                            { type: "function", support: "@wip" },
            "IDBCursorWithValue":                   { type: "function", support: "@wip" },
            "IDBDatabase":                          { type: "function", support: "@wip" },
            "IDBFactory":                           { type: "function", support: "@wip" },
            "IDBIndex":                             { type: "function", support: "@wip" },
            "IDBKeyRange":                          { type: "function", support: "@wip" },
            "IDBObjectStore":                       { type: "function", support: "@wip" },
            "IDBOpenDBRequest":                     { type: "function", support: "@wip" },
            "IDBRequest":                           { type: "function", support: "@wip" },
            "IDBTransaction":                       { type: "function", support: "@wip" },
            "IDBVersionChangeEvent":                { type: "function", support: "@wip" },
            "IIRFilterNode":                        { type: "function", support: "@wip" },
            "IdleDeadline":                         { type: "function" },
            "Image":                                { type: "function" },
            "ImageBitmap":                          { type: "function" },
            "ImageData":                            { type: "function" },
            "Infinity":                             { type: "number" },
            "InputDeviceCapabilities":              { type: "function" },
            "Int16Array":                           { type: "function" },
            "Int32Array":                           { type: "function" },
            "Int8Array":                            { type: "function" },
            "IntersectionObserver":                 { type: "function", support: "@wip" },
            "IntersectionObserverEntry":            { type: "function", support: "@wip" },
            "Intl":                                 { type: "Object" },
            "JSON":                                 { type: "JSON" },
            "KeyboardEvent":                        { type: "function" },
            "Location":                             { type: "function" },
            "MIDIAccess":                           { type: "function" },
            "MIDIConnectionEvent":                  { type: "function" },
            "MIDIInput":                            { type: "function" },
            "MIDIInputMap":                         { type: "function" },
            "MIDIMessageEvent":                     { type: "function" },
            "MIDIOutput":                           { type: "function" },
            "MIDIOutputMap":                        { type: "function" },
            "MIDIPort":                             { type: "function" },
            "Map":                                  { type: "function" },
            "Math":                                 { type: "Math" },
            "MediaDevices":                         { type: "function" },
            "MediaElementAudioSourceNode":          { type: "function" },
            "MediaEncryptedEvent":                  { type: "function" },
            "MediaError":                           { type: "function" },
            "MediaKeyMessageEvent":                 { type: "function" },
            "MediaKeySession":                      { type: "function" },
            "MediaKeyStatusMap":                    { type: "function" },
            "MediaKeySystemAccess":                 { type: "function" },
            "MediaKeys":                            { type: "function" },
            "MediaList":                            { type: "function" },
            "MediaQueryList":                       { type: "function" },
            "MediaQueryListEvent":                  { type: "function" },
            "MediaRecorder":                        { type: "function" },
            "MediaSource":                          { type: "function" },
            "MediaStreamAudioDestinationNode":      { type: "function" },
            "MediaStreamAudioSourceNode":           { type: "function" },
            "MediaStreamEvent":                     { type: "function" },
            "MediaStreamTrack":                     { type: "function" },
            "MessageChannel":                       { type: "function" },
            "MessageEvent":                         { type: "function" },
            "MessagePort":                          { type: "function" },
            "MimeType":                             { type: "function" },
            "MimeTypeArray":                        { type: "function" },
            "MouseEvent":                           { type: "function" },
            "MutationEvent":                        { type: "function", support: false },
            "MutationObserver":                     { type: "function" },
            "MutationRecord":                       { type: "function" },
            "NaN":                                  { type: "number" },
            "NamedNodeMap":                         { type: "function" },
            "Navigator":                            { type: "function" },
            "Node":                                 { type: "function" },
            "NodeFilter":                           { type: "function" },
            "NodeIterator":                         { type: "function" },
            "NodeList":                             { type: "function" },
            "Notification":                         { type: "function" },
            "Number":                               { type: "function" },
            "Object":                               { type: "function" },
            "OfflineAudioCompletionEvent":          { type: "function" },
            "OfflineAudioContext":                  { type: "function" },
            "Option":                               { type: "function" },
            "OscillatorNode":                       { type: "function" },
            "PERSISTENT":                           { type: "number" },
            "PageTransitionEvent":                  { type: "function" },
            "PasswordCredential":                   { type: "function" },
            "Path2D":                               { type: "function" },
            "Performance":                          { type: "function" },
            "PerformanceEntry":                     { type: "function" },
            "PerformanceMark":                      { type: "function" },
            "PerformanceMeasure":                   { type: "function" },
            "PerformanceNavigation":                { type: "function" },
            "PerformanceResourceTiming":            { type: "function" },
            "PerformanceTiming":                    { type: "function" },
            "PeriodicWave":                         { type: "function" },
            "PermissionStatus":                     { type: "function", support: "@wip" },
            "Permissions":                          { type: "function", support: "@wip" },
            "Plugin":                               { type: "function", support: "@wip" },
            "PluginArray":                          { type: "function", support: "@wip" },
            "PopStateEvent":                        { type: "function" },
            "Presentation":                         { type: "function" },
            "PresentationAvailability":             { type: "function" },
            "PresentationConnection":               { type: "function" },
            "PresentationConnectionAvailableEvent": { type: "function" },
            "PresentationConnectionCloseEvent":     { type: "function" },
            "PresentationRequest":                  { type: "function" },
            "ProcessingInstruction":                { type: "function" },
            "ProgressEvent":                        { type: "function" },
            "Promise":                              { type: "function" },
            "PromiseRejectionEvent":                { type: "function" },
            "Proxy":                                { type: "function", support: "@wip" },
            "PushManager":                          { type: "function", support: "@wip" },
            "PushSubscription":                     { type: "function", support: "@wip" },
            "RTCCertificate":                       { type: "function" },
            "RTCIceCandidate":                      { type: "function" },
            "RTCSessionDescription":                { type: "function" },
            "RadioNodeList":                        { type: "function" },
            "Range":                                { type: "function" },
            "RangeError":                           { type: "function" },
            "ReadableByteStream":                   { type: "function" },
            "ReadableStream":                       { type: "function" },
            "ReferenceError":                       { type: "function" },
            "Reflect":                              { type: "Object" },
            "RegExp":                               { type: "function" },
            "Request":                              { type: "function" },
            "Response":                             { type: "function" },
            "SVGAElement":                          { type: "function" },
            "SVGAngle":                             { type: "function" },
            "SVGAnimateElement":                    { type: "function" },
            "SVGAnimateMotionElement":              { type: "function" },
            "SVGAnimateTransformElement":           { type: "function" },
            "SVGAnimatedAngle":                     { type: "function" },
            "SVGAnimatedBoolean":                   { type: "function" },
            "SVGAnimatedEnumeration":               { type: "function" },
            "SVGAnimatedInteger":                   { type: "function" },
            "SVGAnimatedLength":                    { type: "function" },
            "SVGAnimatedLengthList":                { type: "function" },
            "SVGAnimatedNumber":                    { type: "function" },
            "SVGAnimatedNumberList":                { type: "function" },
            "SVGAnimatedPreserveAspectRatio":       { type: "function" },
            "SVGAnimatedRect":                      { type: "function" },
            "SVGAnimatedString":                    { type: "function" },
            "SVGAnimatedTransformList":             { type: "function" },
            "SVGAnimationElement":                  { type: "function" },
            "SVGCircleElement":                     { type: "function" },
            "SVGClipPathElement":                   { type: "function" },
            "SVGComponentTransferFunctionElement":  { type: "function" },
            "SVGCursorElement":                     { type: "function" },
            "SVGDefsElement":                       { type: "function" },
            "SVGDescElement":                       { type: "function" },
            "SVGDiscardElement":                    { type: "function" },
            "SVGElement":                           { type: "function" },
            "SVGEllipseElement":                    { type: "function" },
            "SVGFEBlendElement":                    { type: "function" },
            "SVGFEColorMatrixElement":              { type: "function" },
            "SVGFEComponentTransferElement":        { type: "function" },
            "SVGFECompositeElement":                { type: "function" },
            "SVGFEConvolveMatrixElement":           { type: "function" },
            "SVGFEDiffuseLightingElement":          { type: "function" },
            "SVGFEDisplacementMapElement":          { type: "function" },
            "SVGFEDistantLightElement":             { type: "function" },
            "SVGFEDropShadowElement":               { type: "function" },
            "SVGFEFloodElement":                    { type: "function" },
            "SVGFEFuncAElement":                    { type: "function" },
            "SVGFEFuncBElement":                    { type: "function" },
            "SVGFEFuncGElement":                    { type: "function" },
            "SVGFEFuncRElement":                    { type: "function" },
            "SVGFEGaussianBlurElement":             { type: "function" },
            "SVGFEImageElement":                    { type: "function" },
            "SVGFEMergeElement":                    { type: "function" },
            "SVGFEMergeNodeElement":                { type: "function" },
            "SVGFEMorphologyElement":               { type: "function" },
            "SVGFEOffsetElement":                   { type: "function" },
            "SVGFEPointLightElement":               { type: "function" },
            "SVGFESpecularLightingElement":         { type: "function" },
            "SVGFESpotLightElement":                { type: "function" },
            "SVGFETileElement":                     { type: "function" },
            "SVGFETurbulenceElement":               { type: "function" },
            "SVGFilterElement":                     { type: "function" },
            "SVGForeignObjectElement":              { type: "function" },
            "SVGGElement":                          { type: "function" },
            "SVGGeometryElement":                   { type: "function" },
            "SVGGradientElement":                   { type: "function" },
            "SVGGraphicsElement":                   { type: "function" },
            "SVGImageElement":                      { type: "function" },
            "SVGLength":                            { type: "function" },
            "SVGLengthList":                        { type: "function" },
            "SVGLineElement":                       { type: "function" },
            "SVGLinearGradientElement":             { type: "function" },
            "SVGMPathElement":                      { type: "function" },
            "SVGMarkerElement":                     { type: "function" },
            "SVGMaskElement":                       { type: "function" },
            "SVGMatrix":                            { type: "function" },
            "SVGMetadataElement":                   { type: "function" },
            "SVGNumber":                            { type: "function" },
            "SVGNumberList":                        { type: "function" },
            "SVGPathElement":                       { type: "function" },
            "SVGPatternElement":                    { type: "function" },
            "SVGPoint":                             { type: "function" },
            "SVGPointList":                         { type: "function" },
            "SVGPolygonElement":                    { type: "function" },
            "SVGPolylineElement":                   { type: "function" },
            "SVGPreserveAspectRatio":               { type: "function" },
            "SVGRadialGradientElement":             { type: "function" },
            "SVGRect":                              { type: "function" },
            "SVGRectElement":                       { type: "function" },
            "SVGSVGElement":                        { type: "function" },
            "SVGScriptElement":                     { type: "function" },
            "SVGSetElement":                        { type: "function" },
            "SVGStopElement":                       { type: "function" },
            "SVGStringList":                        { type: "function" },
            "SVGStyleElement":                      { type: "function" },
            "SVGSwitchElement":                     { type: "function" },
            "SVGSymbolElement":                     { type: "function" },
            "SVGTSpanElement":                      { type: "function" },
            "SVGTextContentElement":                { type: "function" },
            "SVGTextElement":                       { type: "function" },
            "SVGTextPathElement":                   { type: "function" },
            "SVGTextPositioningElement":            { type: "function" },
            "SVGTitleElement":                      { type: "function" },
            "SVGTransform":                         { type: "function" },
            "SVGTransformList":                     { type: "function" },
            "SVGUnitTypes":                         { type: "function" },
            "SVGUseElement":                        { type: "function" },
            "SVGViewElement":                       { type: "function" },
            "SVGViewSpec":                          { type: "function" },
            "SVGZoomEvent":                         { type: "function" },
            "Screen":                               { type: "function" },
            "ScreenOrientation":                    { type: "function" },
            "ScriptProcessorNode":                  { type: "function", support: "@wip" },
            "SecurityPolicyViolationEvent":         { type: "function" },
            "Selection":                            { type: "function" },
            "ServiceWorker":                        { type: "function", support: false },
            "ServiceWorkerContainer":               { type: "function", support: false },
            "ServiceWorkerMessageEvent":            { type: "function", support: false },
            "ServiceWorkerRegistration":            { type: "function", support: false },
            "Set":                                  { type: "function" },
            "ShadowRoot":                           { type: "function", support: false },
            "SharedWorker":                         { type: "function", support: false },
            "SourceBuffer":                         { type: "function" },
            "SourceBufferList":                     { type: "function" },
            "SpeechSynthesisEvent":                 { type: "function" },
            "SpeechSynthesisUtterance":             { type: "function" },
            "Storage":                              { type: "function", support: "@wip" },
            "StorageEvent":                         { type: "function", support: "@wip" },
            "String":                               { type: "function" },
            "StyleSheet":                           { type: "function" },
            "StyleSheetList":                       { type: "function" },
            "SubtleCrypto":                         { type: "function" },
            "Symbol":                               { type: "function" },
            "SyncManager":                          { type: "function", support: "@wip" },
            "SyntaxError":                          { type: "function" },
            "TEMPORARY":                            { type: "number" },
            "Text":                                 { type: "function" },
            "TextDecoder":                          { type: "function" },
            "TextEncoder":                          { type: "function" },
            "TextEvent":                            { type: "function" },
            "TextMetrics":                          { type: "function" },
            "TextTrack":                            { type: "function" },
            "TextTrackCue":                         { type: "function" },
            "TextTrackCueList":                     { type: "function" },
            "TextTrackList":                        { type: "function" },
            "TimeRanges":                           { type: "function" },
            "Touch":                                { type: "function" },
            "TouchEvent":                           { type: "function" },
            "TouchList":                            { type: "function" },
            "TrackEvent":                           { type: "function" },
            "TransitionEvent":                      { type: "function" },
            "TreeWalker":                           { type: "function" },
            "TypeError":                            { type: "function" },
            "UIEvent":                              { type: "function" },
            "URIError":                             { type: "function" },
            "URL":                                  { type: "function" },
            "URLSearchParams":                      { type: "function" },
            "Uint16Array":                          { type: "function" },
            "Uint32Array":                          { type: "function" },
            "Uint8Array":                           { type: "function" },
            "Uint8ClampedArray":                    { type: "function" },
            "VTTCue":                               { type: "function" },
            "ValidityState":                        { type: "function" },
            "WallTime":                             { type: "Object", support: false },
            "WaveShaperNode":                       { type: "function" },
            "WeakMap":                              { type: "function" },
            "WeakSet":                              { type: "function" },
            "WebGLActiveInfo":                      { type: "function" },
            "WebGLBuffer":                          { type: "function" },
            "WebGLContextEvent":                    { type: "function" },
            "WebGLFramebuffer":                     { type: "function" },
            "WebGLProgram":                         { type: "function" },
            "WebGLRenderbuffer":                    { type: "function" },
            "WebGLRenderingContext":                { type: "function" },
            "WebGLShader":                          { type: "function" },
            "WebGLShaderPrecisionFormat":           { type: "function" },
            "WebGLTexture":                         { type: "function" },
            "WebGLUniformLocation":                 { type: "function" },
            "WebKitAnimationEvent":                 { type: "function" },
            "WebKitCSSMatrix":                      { type: "function" },
            "WebKitMutationObserver":               { type: "function", support: false },
            "WebKitTransitionEvent":                { type: "function" },
            "WebSocket":                            { type: "function" },
            "WheelEvent":                           { type: "function" },
            "Window":                               { type: "function" },
            "Worker":                               { type: "function", support: "@wip" },
            "XMLDocument":                          { type: "function" },
            "XMLHttpRequest":                       { type: "function" },
            "XMLHttpRequestEventTarget":            { type: "function" },
            "XMLHttpRequestUpload":                 { type: "function" },
            "XMLSerializer":                        { type: "function" },
            "XPathEvaluator":                       { type: "function" },
            "XPathExpression":                      { type: "function" },
            "XPathResult":                          { type: "function" },
            "XSLTProcessor":                        { type: "function" },
            "alert":                                { type: "function" },
            "applicationCache":                     { type: "ApplicationCache", support: "@wip" },
            "atob":                                 { type: "function" },
            "aura":                                 { type: "Object" },
            "blur":                                 { type: "function" },
            "btoa":                                 { type: "function" },
            "caches":                               { type: "CacheStorage", support: "@wip" },
            "cancelAnimationFrame":                 { type: "function" },
            "cancelIdleCallback":                   { type: "function" },
            "captureEvents":                        { type: "function" },
            "chrome":                               { type: "Object" },
            "clearInterval":                        { type: "function" },
            "clearTimeout":                         { type: "function" },
            "clientInformation":                    { type: "Navigator", support: false },
            "close":                                { type: "function" },
            "closed":                               { type: "boolean" },
            "confirm":                              { type: "function" },
            "console":                              { type: "Object" },
            "createImageBitmap":                    { type: "function" },
            "crypto":                               { type: "Crypto" },
            "decodeURI":                            { type: "function" },
            "decodeURIComponent":                   { type: "function" },
            "defaultStatus":                        { type: "string" },
            "defaultstatus":                        { type: "string" },
            "devicePixelRatio":                     { type: "number" },
            "document":                             { type: "HTMLDocument" },
            "encodeURI":                            { type: "function" },
            "encodeURIComponent":                   { type: "function" },
            "escape":                               { type: "function" },
            "eval":                                 { type: "function", support: false },
            "fetch":                                { type: "function" },
            "find":                                 { type: "function" },
            "focus":                                { type: "function" },
            "frameElement":                         { type: "Null" },
            "frames":                               { type: "Window" },
            "getComputedStyle":                     { type: "function" },
            "getMatchedCSSRules":                   { type: "function" },
            "getSelection":                         { type: "function" },
            "history":                              { type: "History" },
            "indexedDB":                            { type: "IDBFactory", support: "@wip" },
            "innerHeight":                          { type: "number" },
            "innerWidth":                           { type: "number" },
            "isFinite":                             { type: "function" },
            "isNaN":                                { type: "function" },
            "isSecureContext":                      { type: "boolean" },
            "length":                               { type: "number" },
            "localStorage":                         { type: "Storage", support: "206" },
            "location":                             { type: "Location" },
            "locationbar":                          { type: "BarProp" },
            "matchMedia":                           { type: "function" },
            "menubar":                              { type: "BarProp" },
            "moveBy":                               { type: "function" },
            "moveTo":                               { type: "function" },
            "name":                                 { type: "string" },
            "navigator":                            { type: "Navigator" },
            "offscreenBuffering":                   { type: "boolean" },
            "onabort":                              { type : "@event" },
            "onanimationend":                       { type : "@event" },
            "onanimationiteration":                 { type : "@event" },
            "onanimationstart":                     { type : "@event" },
            "onautocomplete":                       { type : "@event" },
            "onautocompleteerror":                  { type : "@event" },
            "onbeforeunload":                       { type : "@event" },
            "onblur":                               { type : "@event" },
            "oncancel":                             { type : "@event" },
            "oncanplay":                            { type : "@event" },
            "oncanplaythrough":                     { type : "@event" },
            "onchange":                             { type : "@event" },
            "onclick":                              { type : "@event" },
            "onclose":                              { type : "@event" },
            "oncontextmenu":                        { type : "@event" },
            "oncuechange":                          { type : "@event" },
            "ondblclick":                           { type : "@event" },
            "ondevicemotion":                       { type : "@event" },
            "ondeviceorientation":                  { type : "@event" },
            "ondeviceorientationabsolute":          { type : "@event" },
            "ondrag":                               { type : "@event" },
            "ondragend":                            { type : "@event" },
            "ondragenter":                          { type : "@event" },
            "ondragleave":                          { type : "@event" },
            "ondragover":                           { type : "@event" },
            "ondragstart":                          { type : "@event" },
            "ondrop":                               { type : "@event" },
            "ondurationchange":                     { type : "@event" },
            "onemptied":                            { type : "@event" },
            "onended":                              { type : "@event" },
            "onerror":                              { type: "function" },
            "onfocus":                              { type : "@event" },
            "onhashchange":                         { type : "@event" },
            "oninput":                              { type : "@event" },
            "oninvalid":                            { type : "@event" },
            "onkeydown":                            { type : "@event" },
            "onkeypress":                           { type : "@event" },
            "onkeyup":                              { type : "@event" },
            "onlanguagechange":                     { type : "@event" },
            "onload":                               { type : "@event" },
            "onloadeddata":                         { type : "@event" },
            "onloadedmetadata":                     { type : "@event" },
            "onloadstart":                          { type : "@event" },
            "onmessage":                            { type : "@event" },
            "onmousedown":                          { type : "@event" },
            "onmouseenter":                         { type : "@event" },
            "onmouseleave":                         { type : "@event" },
            "onmousemove":                          { type : "@event" },
            "onmouseout":                           { type : "@event" },
            "onmouseover":                          { type : "@event" },
            "onmouseup":                            { type : "@event" },
            "onmousewheel":                         { type : "@event" },
            "onoffline":                            { type : "@event" },
            "ononline":                             { type : "@event" },
            "onpagehide":                           { type : "@event" },
            "onpageshow":                           { type : "@event" },
            "onpause":                              { type : "@event" },
            "onplay":                               { type : "@event" },
            "onplaying":                            { type : "@event" },
            "onpopstate":                           { type : "@event" },
            "onprogress":                           { type : "@event" },
            "onratechange":                         { type : "@event" },
            "onrejectionhandled":                   { type : "@event" },
            "onreset":                              { type : "@event" },
            "onresize":                             { type : "@event" },
            "onscroll":                             { type : "@event" },
            "onsearch":                             { type : "@event" },
            "onseeked":                             { type : "@event" },
            "onseeking":                            { type : "@event" },
            "onselect":                             { type : "@event" },
            "onshow":                               { type : "@event" },
            "onstalled":                            { type : "@event" },
            "onstorage":                            { type : "@event" },
            "onsubmit":                             { type : "@event" },
            "onsuspend":                            { type : "@event" },
            "ontimeupdate":                         { type : "@event" },
            "ontoggle":                             { type : "@event" },
            "ontransitionend":                      { type : "@event" },
	        "ontouchcancel":               	  		{ type : "@event" },
	        "ontouchend":                	  		{ type : "@event" },
	        "ontouchmove":                	  		{ type : "@event" },
	        "ontouchstart":                	  		{ type : "@event" },
            "onunhandledrejection":                 { type : "@event" },
            "onunload":                             { type : "@event" },
            "onvolumechange":                       { type : "@event" },
            "onwaiting":                            { type : "@event" },
            "onwebkitanimationend":                 { type : "@event", support: false },
            "onwebkitanimationiteration":           { type : "@event", support: false },
            "onwebkitanimationstart":               { type : "@event", support: false },
            "onwebkittransitionend":                { type : "@event", support: false },
            "onwheel":                              { type : "@event" },
            "open":                                 { type: "function" },
            "openDatabase":                         { type: "function", support: "@wip" },
            "opener":                               { type: "Null", support: false },
            "outerHeight":                          { type: "number" },
            "outerWidth":                           { type: "number" },
            "pageStartTime":                        { type: "number" },
            "pageXOffset":                          { type: "number" },
            "pageYOffset":                          { type: "number" },
            "parent":                               { type: "Window" },
            "parseFloat":                           { type: "function" },
            "parseInt":                             { type: "function" },
            "performance":                          { type: "Performance" },
            "personalbar":                          { type: "BarProp" },
            "postMessage":                          { type: "function" },
            "print":                                { type: "function" },
            "prompt":                               { type: "function" },
            "releaseEvents":                        { type: "function" },
            "requestAnimationFrame":                { type: "function" },
            "requestIdleCallback":                  { type: "function" },
            "resizeBy":                             { type: "function" },
            "resizeTo":                             { type: "function" },
            "screen":                               { type: "Screen" },
            "screenLeft":                           { type: "number" },
            "screenTop":                            { type: "number" },
            "screenX":                              { type: "number" },
            "screenY":                              { type: "number" },
            "scroll":                               { type: "function" },
            "scrollBy":                             { type: "function" },
            "scrollTo":                             { type: "function" },
            "scrollX":                              { type: "number" },
            "scrollY":                              { type: "number" },
            "scrollbars":                           { type: "BarProp" },
            "self":                                 { type: "Window" },
            "sessionStorage":                       { type: "Storage", support: "206" },
            "setInterval":                          { type: "function" },
            "setTimeout":                           { type: "function" },
            "speechSynthesis":                      { type: "SpeechSynthesis", support: "@wip" },
            "status":                               { type: "string" },
            "statusbar":                            { type: "BarProp" },
            "stop":                                 { type: "function" },
            "styleMedia":                           { type: "StyleMedia" },
            "toolbar":                              { type: "BarProp" },
            "top":                                  { type: "Window" },
            "undefined":                            { type: "Undefined" },
            "unescape":                             { type: "function", support: false },
            "webkitAudioContext":                   { type: "function", support: false },
            "webkitCancelAnimationFrame":           { type: "function", support: false },
            "webkitCancelRequestAnimationFrame":    { type: "function", support: false },
            "webkitIDBCursor":                      { type: "function", support: false },
            "webkitIDBDatabase":                    { type: "function", support: false },
            "webkitIDBFactory":                     { type: "function", support: false },
            "webkitIDBIndex":                       { type: "function", support: false },
            "webkitIDBKeyRange":                    { type: "function", support: false },
            "webkitIDBObjectStore":                 { type: "function", support: false },
            "webkitIDBRequest":                     { type: "function", support: false },
            "webkitIDBTransaction":                 { type: "function", support: false },
            "webkitIndexedDB":                      { type: "IDBFactory", support: false },
            "webkitMediaStream":                    { type: "function", support: false },
            "webkitOfflineAudioContext":            { type: "function", support: false },
            "webkitRTCPeerConnection":              { type: "function", support: false },
            "webkitRequestAnimationFrame":          { type: "function", support: false },
            "webkitRequestFileSystem":              { type: "function", support: false },
            "webkitResolveLocalFileSystemURL":      { type: "function", support: false },
            "webkitSpeechGrammar":                  { type: "function", support: false },
            "webkitSpeechGrammarList":              { type: "function", support: false },
            "webkitSpeechRecognition":              { type: "function", support: false },
            "webkitSpeechRecognitionError":         { type: "function", support: false },
            "webkitSpeechRecognitionEvent":         { type: "function", support: false },
            "webkitStorageInfo":                    { type: "DeprecatedStorageInfo", support: false },
            "webkitURL":                            { type: "function", support: false },
            "window":                               { type: "Window" }
        },
        "EventTarget": {
            "addEventListener":                 { type: "function" },
            "dispatchEvent":                    { type: "function" },
            "removeEventListener":              { type: "function" }
        }
    }
})