this["Perf"]&&void 0!==this["Perf"].enabled||(function(window){'use strict';/*
 Copyright (c) 2011, Yahoo! Inc.  All rights reserved.
 Copyright (c) 2012, Log-Normal, Inc.  All rights reserved.
 Copyright (c) 2013, SOASTA, Inc. All rights reserved.
 Copyright (c) 2013, Salesforce.com. All rights reserved.
 Copyrights licensed under the BSD License. See the accompanying LICENSE.txt file for terms.
*/
var e=(new Date).getTime(),m;
(function(c){c.parent!==c&&document.getElementById("boomr-if-as")&&"script"===document.getElementById("boomr-if-as").nodeName.toLowerCase()&&(c=c.parent);var f=c.document,a=c.perfOptions||{},d={t:"",$:c.location.hostname.replace(/.*?([^.]+\.[^.]+)\.?$/,"$1").toLowerCase(),xa:"",k:!1,W:!1,A:{page_ready:[],page_unload:[],dom_loaded:[],onLoad:[],visibility_changed:[],before_beacon:[],click:[]},f:{},w:{},ka:function(b){var a;b||(b=c.event);b.target?a=b.target:b.srcElement&&(a=b.srcElement);!a||"OBJECT"===
a.nodeName.toUpperCase()&&"application/x-shockwave-flash"===a.type||(3===a.nodeType&&(a=a.parentNode),d.fireEvent("click",a))},fireEvent:function(b,a){var c,f,k;if(!d.A.hasOwnProperty(b))return!1;k=d.A[b];for(c=0;c<k.length;c++)f=k[c],f[0].call(f[2],a,f[1]);return!0}},b={m:void 0,g:e,aa:null,plugins:{},version:"0.9",window:c,c:{C:function(b,a){var c=[],d;if(!b||"object"!==typeof b)return b;void 0===a&&(a="\n\t");for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&c.push(encodeURIComponent(d)+"="+
encodeURIComponent(b[d]));return c.join(a)},I:function(b){if(!b)return null;b=" "+b+"=";var a,c;c=" "+f.cookie+";";return 0<=(a=c.indexOf(b))?(a+=b.length,c=c.substring(a,c.indexOf(";",a))):null},setCookie:function(a,c,h){var l,k,n;if(!a||!d.$)return!1;c=b.c.C(c,"&");l=a+"="+c;k=[l,"path=/","domain="+d.$];h&&(n=new Date,n.setTime(n.getTime()+1E3*h),n=n.toGMTString(),k.push("expires="+n));return 4E3>l.length?(f.cookie=k.join("; "),c===b.c.I(a)):!1},S:function(b){var a,c,d,f={};if(!b)return null;b=
b.split("&");if(0===b.length)return null;a=0;for(c=b.length;a<c;a++)d=b[a].split("="),d.push(""),f[decodeURIComponent(d[0])]=decodeURIComponent(d[1]);return f},na:function(a){return b.c.setCookie(a,{},0)},ma:function(b,a,c,d){var f,n=0;if(!a||!a[c])return!1;for(f=0;f<d.length;f++)void 0!==a[c][d[f]]&&(b[d[f]]=a[c][d[f]],n++);return 0<n},addListener:function(b,a,c){b.addEventListener?b.addEventListener(a,c,!1):b.attachEvent("on"+a,c)}},j:function(a){var g,h=null,l=["beacon_url","site_domain","user_ip"];
a||(a={});for(g=0;g<l.length;g++)void 0!==a[l[g]]&&(d[l[g]]=a[l[g]]);void 0!==a.log&&(b.log=a.log);b.log||(b.log=function(){});for(h in b.plugins)b.plugins.hasOwnProperty(h)&&(a[h]&&a[h].hasOwnProperty("enabled")&&!1===a[h].enabled?d.w[h]=1:(d.w[h]&&delete d.w[h],"function"===typeof b.plugins[h].j&&b.plugins[h].j(a)));if(d.W)return b;d.k||void 0!==a.P&&!1===a.P||(f.readyState&&"complete"===f.readyState?b.setImmediate(b.D,null,null,b):c.onpagehide||null===c.onpagehide?b.c.addListener(c,"pageshow",
b.D):b.c.addListener(c,"load",b.D));b.c.addListener(c,"DOMContentLoaded",function(){d.fireEvent("dom_loaded")});(function(){function a(){d.fireEvent("visibility_changed")}f.webkitVisibilityState?b.c.addListener(f,"webkitvisibilitychange",a):f.msVisibilityState?b.c.addListener(f,"msvisibilitychange",a):f.visibilityState&&b.c.addListener(f,"visibilitychange",a);b.c.addListener(f,"mouseup",d.ka);c.onpagehide||null===c.onpagehide||b.c.addListener(c,"unload",function(){delete b.window})})();d.W=!0;return b},
D:function(){if(d.k)return b;d.fireEvent("page_ready");d.k=!0;return b},setImmediate:function(b,a,d,f){function k(){b.call(f||null,a,d||{});k=null}c.setImmediate?c.setImmediate(k):c.msSetImmediate?c.msSetImmediate(k):c.webkitSetImmediate?c.webkitSetImmediate(k):c.mozSetImmediate?c.mozSetImmediate(k):setTimeout(k,10)},subscribe:function(a,g,f,l){var k,n,s;if(!d.A.hasOwnProperty(a))return b;s=d.A[a];for(k=0;k<s.length;k++)if(n=s[k],n[0]===g&&n[1]===f&&n[2]===l)return b;s.push([g,f||{},l||null]);"page_ready"===
a&&d.k&&b.setImmediate(g,null,f,l);"page_unload"===a&&(a=function(a){g&&g.call(l,a||c.event,f)},c.onpagehide||null===c.onpagehide?b.c.addListener(c,"pagehide",a):b.c.addListener(c,"unload",a),b.c.addListener(c,"beforeunload",a));return b},d:function(a,c){if("string"===typeof a)d.f[a]=c;else if("object"===typeof a)for(var f in a)a.hasOwnProperty(f)&&(d.f[f]=a[f]);return b},oa:function(a){var c,f;if(!arguments.length)return b;f=1===arguments.length&&"[object Array]"===Object.prototype.toString.apply(a)?
a:arguments;for(c=0;c<f.length;c++)d.f.hasOwnProperty(f[c])&&delete d.f[f[c]];return b},U:function(){return d.f},ha:function(a){return d.f[a]},removeStats:function(){d.f={};b.plugins.b.da();return b},F:function(){var a,g,h=0;for(a in b.plugins)if(b.plugins.hasOwnProperty(a)&&!d.w[a]&&!b.plugins[a].B())return b;d.f.v=b.version;d.f.u=f.URL.replace(/#.*/,"");c!==window&&(d.f["if"]="");d.fireEvent("before_beacon",d.f);if(!d.t)return b;g=[];for(a in d.f)d.f.hasOwnProperty(a)&&(h++,g.push(encodeURIComponent(a)+
"="+(void 0===d.f[a]||null===d.f[a]?"":encodeURIComponent(d.f[a]+""))));g=d.t+(-1<d.t.indexOf("?")?"&":"?")+g.join("&");b.debug("Sending url: "+g.replace(/&/g,"\n\t"));h&&(a=new Image,a.src=g);return b},qa:function(a){d.t=a}};b.m="number"===typeof a.BOOMR_lstart?a.BOOMR_lstart:0;delete a.BOOMR_lstart;(function(){function a(c){return function(a,d){b.log(a,c,"boomerang"+(d?"."+d:""));return b}}b.debug=a("debug");b.info=a("info");b.warn=a("warn");b.error=a("error")})();c.G&&c.G.ta&&c.G.ta.ua?b.log=c.G.log:
c.O&&c.O.log?b.log=c.O.log:"object"===typeof c.console&&void 0!==c.console.log&&(b.log=function(a,b,d){c.console.log(d+": ["+b+"] "+a)});m=b})(window);(function(c){var f=c.document;m=m||{};m.plugins=m.plugins||{};var a={Y:!1,k:!1,ya:!1,complete:!1,a:{},cookie:"RT",ea:1800,ra:!1,navigationType:0,navigationStart:void 0,responseStart:void 0,K:Math.floor(4294967296*Math.random()).toString(36),l:void 0,L:0,g:void 0,p:void 0,n:void 0,q:void 0,setCookie:function(b,c){var d,h;if(!a.cookie)return a;d=m.c.S(m.c.I(a.cookie))||{};if("ul"===b||"hd"===b)d.r=f.URL.replace(/#.*/,"");"cl"===b&&(c?d.nu=c:d.nu&&delete d.nu);!1===c&&delete d.nu;h=(new Date).getTime();
b&&(d[b]=h);m.debug("Setting cookie "+m.c.C(d),"rt");if(!m.c.setCookie(a.cookie,d,a.ea))return m.error("cannot set start cookie","rt"),a;d=(new Date).getTime();50<d-h&&(m.c.na(a.cookie),m.error("took more than 50ms to set cookie... aborting: "+h+" -> "+d,"rt"));return a},X:function(){var b;a.cookie&&(b=m.c.S(m.c.I(a.cookie)))&&(b.s=Math.max(+b.ul||0,+b.cl||0),m.debug("Read from cookie "+m.c.C(b),"rt"),b.s&&(b.r||b.nu)&&(a.n=b.r,m.debug(a.n+" =?= "+a.q,"rt"),m.debug(b.s+" <? "+(+b.cl+15),"rt"),m.debug(b.nu+
" =?= "+f.URL.replace(/#.*/,""),"rt"),!a.ra||a.n===a.q||b.s<+b.cl+15&&b.nu===f.URL.replace(/#.*/,"")?(a.g=b.s,+b.hd>b.s&&(a.p=parseInt(b.hd,10))):a.g=a.p=void 0),b.sid&&(a.K=b.sid),b.ss&&(a.l=parseInt(b.ss,10)),b.sl&&(a.L=parseInt(b.sl,10)))},ca:function(){if(!(f.webkitVisibilityState&&"prerender"===f.webkitVisibilityState||f.msVisibilityState&&3===f.msVisibilityState))return!1;m.plugins.b.o("t_load",a.navigationStart);m.plugins.b.e("t_load");m.plugins.b.o("t_prerender",a.navigationStart);m.plugins.b.o("t_postrender");
m.subscribe("visibility_changed",m.plugins.b.h,null,m.plugins.b);return!0},ia:function(){var b,d,f;a.navigationStart||((d=c.performance||c.msPerformance||c.webkitPerformance||c.mozPerformance)&&d.navigation&&(a.navigationType=d.navigation.type),d&&d.timing?b=d.timing:c.H&&c.H.csi&&c.H.csi().startE?(b={navigationStart:c.H.csi().startE},f="csi"):c.V&&c.V.startE()&&(b={navigationStart:c.V.startE()},f="gtb"),b?(m.d("rt.start",f||"navigation"),a.navigationStart=b.navigationStart||b.fetchStart||void 0,
a.responseStart=b.responseStart||void 0,navigator.userAgent.match(/Firefox\/[78]\./)&&(a.navigationStart=b.unloadEventStart||b.fetchStart||void 0)):m.warn("This browser doesn't support the WebTiming API","rt"))},la:function(b){m.debug("Unload called with "+m.c.C(b),"rt");a.setCookie("beforeunload"===b.type?"ul":"hd")},onclick:function(b){if(b){for(m.debug("Click called with "+b.nodeName,"rt");b&&"A"!==b.nodeName.toUpperCase();)b=b.parentNode;b&&"A"===b.nodeName.toUpperCase()&&(m.debug("passing through",
"rt"),a.setCookie("cl",b.href))}},fa:function(){m.plugins.b.e("t_domloaded")},onLoad:function(){m.plugins.b.e("t_onLoad")}},d=m.plugins.b={j:function(b){m.debug("init RT","rt");c!==m.window&&(c=m.window,f=c.document);m.c.ma(a,b,"RT",["cookie","cookie_exp","strict_referrer"]);a.X();if(a.Y)return d;a.complete=!1;a.a={};m.subscribe("page_ready",d.h,null,d);m.subscribe("dom_loaded",a.fa,null,a);m.subscribe("page_unload",a.la,null,a);m.subscribe("click",a.onclick,null,a);m.subscribe("onLoad",a.onLoad,
null,a);m.g&&(d.o("boomerang",m.g),d.e("boomerang",m.aa),d.e("boomr_fb",m.g),m.m&&(d.e("kylie_ld",m.m),d.setTimer("kylie_lat",m.g-m.m,m.m)));a.n=a.q=f.referrer.replace(/#.*/,"");a.l||(a.l=m.m||m.g);a.Y=!0;return d},o:function(b,c){b&&("t_page"===b&&d.e("t_resp",c),a.a[b]={start:"number"===typeof c?c:(new Date).getTime()},a.complete=!1);return d},e:function(b,c){b&&(a.a[b]=a.a[b]||{},void 0===a.a[b].end&&(a.a[b].end="number"===typeof c?c:(new Date).getTime()));return d},setTimer:function(b,c,f){b&&
(a.a[b]={i:c,start:f});return d},sa:function(b,c){b&&(a.a[c]=a.a[b],a.a[b]={})},da:function(){a.a={};return d},N:function(){if(a.a){var b,c;for(c in a.a)a.a.hasOwnProperty(c)&&(b=a.a[c],b.end&&b.start&&("number"!==typeof b.i&&(b.i=b.end-b.start),m.d(c,b.i)))}},T:function(){return a.a},startTransaction:function(a){return m.plugins.b.o("txn_"+a,(new Date).getTime())},endTransaction:function(a){return m.plugins.b.e("txn_"+a,(new Date).getTime())},ga:function(){return a.K},R:function(){return a.l},isOnLoadFired:function(){return a.k},
h:function(){m.debug("Called done","rt");var b,c=(new Date).getTime(),f=0,h,l=[];a.complete=!1;a.X();a.ia();if(a.ca())return d;a.responseStart?(d.e("t_resp",a.responseStart),a.a.t_load?d.setTimer("t_page",a.a.t_load.end-a.responseStart,a.responseStart):(b=c-a.responseStart,0<b&&d.setTimer("t_page",b,a.responseStart))):a.a.hasOwnProperty("t_page")?d.e("t_page"):a.p&&(d.e("t_resp",a.p),d.setTimer("t_page",c-a.p,a.p));a.a.hasOwnProperty("t_postrender")&&(d.e("t_postrender"),d.e("t_prerender"));a.navigationStart?
b=a.navigationStart:a.g&&2!==a.navigationType?(b=a.g,m.d("rt.start","cookie")):(m.d("rt.start","none"),b=void 0);b&&a.l>b&&(a.l=m.m||m.g,a.L=0);d.e("t_done",c);m.oa("t_done","t_page","t_resp","r","r2","rt.tstart","rt.bstart","rt.end","rt.ss","rt.sl","rt.lt","t_postrender","t_prerender","t_load");m.d("rt.tstart",b);m.d("rt.bstart",m.g);m.d("rt.end",a.a.t_done.end);a.a.t_configfb&&("t_configfb"in a.a&&"number"!=typeof a.a.t_configfb.start||isNaN(a.a.t_configfb.start))&&("t_configjs"in a.a&&"number"==
typeof a.a.t_configjs.start?a.a.t_configfb.start=a.a.t_configjs.start:delete a.a.t_configfb);for(h in a.a)a.a.hasOwnProperty(h)&&(c=a.a[h],"number"!==typeof c.i&&("number"!==typeof c.start&&(c.start=b),c.i=c.end-c.start),isNaN(c.i)||(m.d(h,c.i),f++));f&&(m.d("r",a.n),a.q!==a.n&&m.d("r2",a.q),l.length&&m.d("t_other",l.join(",")));m.d({"rt.sid":a.K,"rt.ss":a.l,"rt.sl":a.L});a.a={};a.complete=!0;m.F();a.k=!0;return d},B:function(){return a.complete}}})(window);(function(){m=m||{};m.plugins=m.plugins||{};var c={complete:!1,h:function(){var a=m.window,d=a.performance,b=a.console,f=a.document,g="[object Opera]"==={}.toString.call(a.opera)?f.querySelectorAll:f.getElementsByTagName,a=void 0===g.call?function(a){return g(a)}:g;(d=d&&d.memory?d.memory:b&&b.memory?b.memory:null)&&m.d({"mem.total":d.totalJSHeapSize,"mem.used":d.usedJSHeapSize});m.d({"dom.ln":a.call(f,"*").length,"dom.sz":a.call(f,"html")[0].innerHTML.length,"dom.img":a.call(f,"img").length,"dom.script":a.call(f,
"script").length});c.complete=!0;m.F()}},f=m.plugins.va={j:function(){m.subscribe("page_ready",c.h,null,c);return f},B:function(){return c.complete}}})();(function(){m=m||{};m.plugins=m.plugins||{};var c={complete:!1,h:function(){var a=m.window,d,b;(d=a.performance||a.msPerformance||a.webkitPerformance||a.mozPerformance)&&d.timing&&d.navigation&&(m.info("This user agent supports NavigationTiming.","nt"),b=d.navigation,d=d.timing,b={nt_red_cnt:b.redirectCount,nt_nav_type:b.type,nt_nav_st:d.navigationStart,nt_red_st:d.redirectStart,nt_red_end:d.redirectEnd,nt_fet_st:d.fetchStart,nt_dns_st:d.domainLookupStart,nt_dns_end:d.domainLookupEnd,nt_con_st:d.connectStart,
nt_con_end:d.connectEnd,nt_req_st:d.requestStart,nt_res_st:d.responseStart,nt_res_end:d.responseEnd,nt_domloading:d.domLoading,nt_domint:d.domInteractive,nt_domcontloaded_st:d.domContentLoadedEventStart,nt_domcontloaded_end:d.domContentLoadedEventEnd,nt_domcomp:d.domComplete,nt_load_st:d.loadEventStart,nt_load_end:d.loadEventEnd,nt_unload_st:d.unloadEventStart,nt_unload_end:d.unloadEventEnd},d.secureConnectionStart&&(b.nt_ssl_st=d.secureConnectionStart),d.ja&&(b.nt_first_paint=d.ja),m.d(b));a.chrome&&
a.chrome.loadTimes&&(d=a.chrome.loadTimes())&&(b={nt_spdy:d.wasFetchedViaSpdy?1:0,nt_first_paint:d.firstPaintTime},m.d(b));c.complete=!0;m.F()}},f=m.plugins.wa={j:function(){m.subscribe("page_ready",c.h,null,c);return f},B:function(){return c.complete}}})();m.d("mob.ct","object"===typeof navigator&&navigator.connection?navigator.connection.type:0);(function(){m=m||{};m.plugins=m.plugins||{};var c={Q:m.window.document,Z:"script",complete:!1,J:!1,M:void 0,h:function(){c.complete||(c.complete=!0,c.J=!1,m.F())},pa:function(){var a=c.Q.getElementsByTagName(c.Z)[0],d=c.Q.createElement(c.Z);c.M=(new Date).getTime();d.src=m.window.BOOMR_cURL;a.parentNode.insertBefore(d,a)}},f=m.plugins.ba={j:function(){if(c.complete)return f;if(c.J)return setTimeout(c.h,10),m.d("t_cjs",(new Date).getTime()-c.M),p.BOOMR_configt&&(m.d("t_cfb",p.BOOMR_configt-c.M),delete p.BOOMR_configt),
f;c.J=!0;m.subscribe("page_ready",c.pa,null,null);return f},B:function(){return c.complete}}})();m.j({log:null,za:!0,ba:{enabled:!1},P:!1});m.aa=(new Date).getTime();var q={DEBUG:{name:"DEBUG",value:1},INTERNAL:{name:"INTERNAL",value:2},PRODUCTION:{name:"PRODUCTION",value:3},DISABLED:{name:"DISABLED",value:4}},t={PAGE_START_MARK:"PageStart",PERF_PAYLOAD_PARAM:"bulkPerf",MARK_NAME:"mark",MEASURE_NAME:"measure",MARK_START_TIME:"st",MARK_LAST_TIME:"lt",PAGE_NAME:"pn",ELAPSED_TIME:"et",REFERENCE_TIME:"rt",Perf_LOAD_DONE:"loadDone",STATS:{NAME:"stat",SERVER_ELAPSED:"internal_serverelapsed",DB_TOTAL_TIME:"internal_serverdbtotaltime",DB_CALLS:"internal_serverdbcalls",
DB_FETCHES:"internal_serverdbfetches"}};window.PerfConstants=t;window.PerfLogLevel=q;var p=window.perfOptions;p?(p.pageStartTime||(p.pageStartTime=(new Date).getTime()),p.bURL&&m.qa(p.bURL)):p={pageStartTime:(new Date).getTime()};var u=null;function v(c){"string"===typeof c&&(c=q[c]);return c||q.INTERNAL}function w(c,f){m.plugins.b.sa(c,f);return x}
var x={currentLogLevel:v(p.logLevel),startTime:p.pageStartTime,mark:function(c,f){x.currentLogLevel.value<=v(f).value&&m.plugins.b.o(c);return x},endMark:function(c,f){x.currentLogLevel.value<=v(f).value&&m.plugins.b.e(c);return x},updateMarkName:w,setTimer:function(c,f,a){x.currentLogLevel.value<=v(a).value&&(0<=f?m.plugins.b.setTimer(c,f):m.plugins.b.e(c));return x},measureToJson:function(c){return"{"+t.MEASURE_NAME+':"'+c[t.MEASURE_NAME]+'",'+t.MARK_NAME+':"'+c[t.MARK_NAME]+'",'+t.ELAPSED_TIME+
":"+c[t.ELAPSED_TIME]+","+t.REFERENCE_TIME+":"+c[t.REFERENCE_TIME]+"}"},toJson:function(c){m.plugins.b.N();var f=m.plugins.b.T(),a=m.plugins.b.R(),d=["{",'sessionID:"',m.plugins.b.ga(),'",',"st:",a,",",'pn:"',window.document.URL,'",','uid:"',Math.round(1E15*Math.random()).toString(),'",'],b=[],r=[],g,h,l=m.U(),k;for(g in l)"r"!=g&&"r2"!=g&&"t_other"!=g&&l.hasOwnProperty(g)&&!isNaN(l[g])&&(c&&b.push('"'+g+'":'+l[g]),h={},h[t.MEASURE_NAME]=g,h[t.MARK_NAME]=g,h[t.ELAPSED_TIME]=l[g],k=f[g],h[t.REFERENCE_TIME]=
k&&k.start?k.start:a,r.push(x.measureToJson(h)));c&&d.push("marks:{",b.join(","),"},");d.push("measures:[",r.join(","),"]}");return d.join("")},toPostVar:function(){return t.PERF_PAYLOAD_PARAM+"="+x.toJson().replace(/&/g,"__^__")},getMeasures:function(){m.plugins.b.N();var c=m.plugins.b.T(),f=m.plugins.b.R(),a=[],d=m.U(),b,r;for(b in d)"r"!=b&&"r2"!=b&&"t_other"!=b&&d.hasOwnProperty(b)&&!isNaN(d[b])&&(r={},r[t.MEASURE_NAME]=b,r[t.MARK_NAME]=b,r[t.ELAPSED_TIME]=d[b],r[t.REFERENCE_TIME]=c[b]?c[b].start:
f,a.push(r));return a},getBeaconData:function(){return u},setBeaconData:function(c){u=c},clearBeaconData:function(){u=null},removeStats:m.removeStats,subscribe:m.subscribe,stat:function(c,f){m.d("st_"+c,f);return x},getStat:function(c){m.plugins.b.N();return c?m.ha(c):-1},onLoad:m.D,startTransaction:function(c){m.plugins.b.startTransaction(c);return x},endTransaction:function(c){m.plugins.b.endTransaction(c);return x},updateTransaction:w,isOnLoadFired:m.plugins.b.isOnLoadFired,util:{setCookie:function(c,
f,a,d){document.cookie=c+"="+escape(f+"")+(a?"; expires="+a.toGMTString():"")+(d?"; path="+d:"; path=/")}},enabled:!0};window.Perf=x;window.PerfLogLevel=q;window.PerfConstants=t;})(this);
//# sourceMappingURL=perf.js.map