({
    testName: {
        "systemAPI": "HTMLDocument",
        "secureAPI": "SecureDocument"
    },
    testPlan: {
        "HTMLDocument" : {
            // Defined on Instance
            "location":                         {type: "Location" },
            // Defined on Proto
            "fgColor":                          {type: "string" },
            "linkColor":                        {type: "string" },
            "vlinkColor":                       {type: "string" },
            "alinkColor":                       {type: "string" },
            "bgColor":                          {type: "string" },
            "all":                              {type: "HTMLAllCollection" },
            "clear":                            {type: "function" },
            "captureEvents":                    {type: "function" },
            "releaseEvents":                    {type: "function" }
        },
        "Document" : {
            "URL":                              {type: "string" },
            "activeElement":                    {type: "HTMLBodyElement" },
            "adoptNode":                        {type: "function" },
            "anchors":                          {type: "HTMLCollection" },
            "applets":                          {type: "HTMLCollection" },
            "body":                             {type: "HTMLBodyElement",   support: true },
            "caretRangeFromPoint":              {type: "function" },
            "characterSet":                     {type: "string" },
            "charset":                          {type: "string" },
            "childElementCount":                {type: "number" },
            "children":                         {type: "HTMLCollection" },
            "close":                            {type: "function" },
            "compatMode":                       {type: "string" },
            "contentType":                      {type: "string" },
            "cookie":                           {type: "string",            support: true },
            "createAttribute":                  {type: "function" },
            "createAttributeNS":                {type: "function" },
            "createCDATASection":               {type: "function" },
            "createComment":                    {type: "function",          support: true },
            "createDocumentFragment":           {type: "function",          support: true },
            "createElement":                    {type: "function",          support: true },
            "createElementNS":                  {type: "function",          support: true },
            "createEvent":                      {type: "function",          support: true },
            "createExpression":                 {type: "function" },
            "createNSResolver":                 {type: "function" },
            "createNodeIterator":               {type: "function" },
            "createProcessingInstruction":      {type: "function" },
            "createRange":                      {type: "function" },
            "createTextNode":                   {type: "function",          support: true },
            "createTreeWalker":                 {type: "function" },
            "currentScript":                    {type: "HTMLScriptElement|Null", skip: true },
            "defaultView":                      {type: "Window",            support: true },
            "designMode":                       {type: "string" },
            "dir":                              {type: "string" },
            "doctype":                          {type: "DocumentType" },
            "documentElement":                  {type: "HTMLHtmlElement",   support: true },
            "documentURI":                      {type: "string" },
            "domain":                           {type: "string" },
            "elementFromPoint":                 {type: "function" },
            "elementsFromPoint":                {type: "function" },
            "embeds":                           {type: "HTMLCollection" },
            "evaluate":                         {type: "function" },
            "execCommand":                      {type: "function" },
            "exitPointerLock":                  {type: "function" },
            "firstElementChild":                {type: "HTMLHtmlElement" },
            "fonts":                            {type: "FontFaceSet" },
            "forms":                            {type: "HTMLCollection" },
            "getElementById":                   {type: "function",          support: true },
            "getElementsByClassName":           {type: "function",          support: true },
            "getElementsByName":                {type: "function",          support: true },
            "getElementsByTagName":             {type: "function",          support: true },
            "getElementsByTagNameNS":           {type: "function",          support: true },
            "getSelection":                     {type: "function" },
            "hasFocus":                         {type: "function" },
            "head":                             {type: "HTMLHeadElement",   support: true },
            "hidden":                           {type: "boolean" },
            "images":                           {type: "HTMLCollection" },
            "implementation":                   {type: "DOMImplementation" },
            "importNode":                       {type: "function" },
            "inputEncoding":                    {type: "string" },
            "lastElementChild":                 {type: "HTMLHtmlElement" },
            "lastModified":                     {type: "string" },
            "links":                            {type: "HTMLCollection" },
            "onabort":                          {type: "Null" },
            "onautocomplete":                   {type: "Null" },
            "onautocompleteerror":              {type: "Null" },
            "onbeforecopy":                     {type: "Null" },
            "onbeforecut":                      {type: "Null" },
            "onbeforepaste":                    {type: "Null" },
            "onblur":                           {type: "Null" },
            "oncancel":                         {type: "Null" },
            "oncanplay":                        {type: "Null" },
            "oncanplaythrough":                 {type: "Null" },
            "onchange":                         {type: "Null" },
            "onclick":                          {type: "Null" },
            "onclose":                          {type: "Null" },
            "oncontextmenu":                    {type: "Null" },
            "oncopy":                           {type: "Null" },
            "oncuechange":                      {type: "Null" },
            "oncut":                            {type: "Null" },
            "ondblclick":                       {type: "Null" },
            "ondrag":                           {type: "Null" },
            "ondragend":                        {type: "Null" },
            "ondragenter":                      {type: "Null" },
            "ondragleave":                      {type: "Null" },
            "ondragover":                       {type: "Null" },
            "ondragstart":                      {type: "Null" },
            "ondrop":                           {type: "Null" },
            "ondurationchange":                 {type: "Null" },
            "onemptied":                        {type: "Null" },
            "onended":                          {type: "Null" },
            "onerror":                          {type: "Null" },
            "onfocus":                          {type: "Null" },
            "oninput":                          {type: "Null" },
            "oninvalid":                        {type: "Null" },
            "onkeydown":                        {type: "Null" },
            "onkeypress":                       {type: "Null" },
            "onkeyup":                          {type: "Null" },
            "onload":                           {type: "Null" },
            "onloadeddata":                     {type: "Null" },
            "onloadedmetadata":                 {type: "Null" },
            "onloadstart":                      {type: "Null" },
            "onmousedown":                      {type: "Null" },
            "onmouseenter":                     {type: "Null" },
            "onmouseleave":                     {type: "Null" },
            "onmousemove":                      {type: "Null" },
            "onmouseout":                       {type: "Null" },
            "onmouseover":                      {type: "Null" },
            "onmouseup":                        {type: "Null" },
            "onmousewheel":                     {type: "Null" },
            "onpaste":                          {type: "Null" },
            "onpause":                          {type: "Null" },
            "onplay":                           {type: "Null" },
            "onplaying":                        {type: "Null" },
            "onpointerlockchange":              {type: "Null" },
            "onpointerlockerror":               {type: "Null" },
            "onprogress":                       {type: "Null" },
            "onratechange":                     {type: "Null" },
            "onreadystatechange":               {type: "Null" },
            "onreset":                          {type: "Null" },
            "onresize":                         {type: "Null" },
            "onscroll":                         {type: "Null" },
            "onsearch":                         {type: "Null" },
            "onseeked":                         {type: "Null" },
            "onseeking":                        {type: "Null" },
            "onselect":                         {type: "Null" },
            "onselectionchange":                {type: "Null" },
            "onselectstart":                    {type: "Null" },
            "onshow":                           {type: "Null" },
            "onstalled":                        {type: "Null" },
            "onsubmit":                         {type: "Null" },
            "onsuspend":                        {type: "Null" },
            "ontimeupdate":                     {type: "Null" },
            "ontoggle":                         {type: "Null" },
            "onvolumechange":                   {type: "Null" },
            "onwaiting":                        {type: "Null" },
            "onwebkitfullscreenchange":         {type: "Null" },
            "onwebkitfullscreenerror":          {type: "Null" },
            "onwheel":                          {type: "Null" },
            "open":                             {type: "function" },
            "origin":                           {type: "string" },
            "plugins":                          {type: "HTMLCollection" },
            "pointerLockElement":               {type: "Null" },
            "preferredStylesheetSet":           {type: "Null" },
            "queryCommandEnabled":              {type: "function" },
            "queryCommandIndeterm":             {type: "function" },
            "queryCommandState":                {type: "function" },
            "queryCommandSupported":            {type: "function" },
            "queryCommandValue":                {type: "function" },
            "querySelector":                    {type: "function",          support: true,
                                                                            empty: {args: "#none", value: "null"},
                                                                            opaque: {args: "#tic", value: "null"}
                                                },
            "querySelectorAll":                 {type: "function",          support: true,
                                                                            empty: {args: "#none", value: "{}"},
                                                                            opaque: {args: "#tic", value: "{}"}
                                                },
            "readyState":                       {type: "string" },
            "referrer":                         {type: "string" },
            "registerElement":                  {type: "function" },
            "rootElement":                      {type: "Null" },
            "scripts":                          {type: "HTMLCollection" },
            "scrollingElement":                 {type: "HTMLBodyElement" },
            "selectedStylesheetSet":            {type: "Null" },
            "styleSheets":                      {type: "StyleSheetList" },
            "title":                            {type: "string",            support: true },
            "visibilityState":                  {type: "string" },
            "webkitCancelFullScreen":           {type: "function" },
            "webkitCurrentFullScreenElement":   {type: "Null" },
            "webkitExitFullscreen":             {type: "function" },
            "webkitFullscreenElement":          {type: "Null" },
            "webkitFullscreenEnabled":          {type: "boolean" },
            "webkitHidden":                     {type: "boolean" },
            "webkitIsFullScreen":               {type: "boolean" },
            "webkitVisibilityState":            {type: "string" },
            "write":                            {type: "function" },
            "writeln":                          {type: "function" },
            "xmlEncoding":                      {type: "Null" },
            "xmlStandalone":                    {type: "boolean" },
            "xmlVersion":                       {type: "Null" }
        },
        "Node": {
            "ATTRIBUTE_NODE":                   {type: "number" },
            "CDATA_SECTION_NODE":               {type: "number" },
            "COMMENT_NODE":                     {type: "number" },
            "DOCUMENT_FRAGMENT_NODE":           {type: "number" },
            "DOCUMENT_NODE":                    {type: "number" },
            "DOCUMENT_POSITION_CONTAINED_BY":   {type: "number" },
            "DOCUMENT_POSITION_CONTAINS":       {type: "number" },
            "DOCUMENT_POSITION_DISCONNECTED":   {type: "number" },
            "DOCUMENT_POSITION_FOLLOWING":      {type: "number" },
            "DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC":
                                                {type: "number" },
            "DOCUMENT_POSITION_PRECEDING":      {type: "number" },
            "DOCUMENT_TYPE_NODE":               {type: "number" },
            "ELEMENT_NODE":                     {type: "number" },
            "ENTITY_NODE":                      {type: "number" },
            "ENTITY_REFERENCE_NODE":            {type: "number" },
            "NOTATION_NODE":                    {type: "number" },
            "PROCESSING_INSTRUCTION_NODE":      {type: "number" },
            "TEXT_NODE":                        {type: "number" },
            "appendChild":                      {type: "function" },
            "baseURI":                          {type: "string" },
            "childNodes":                       {type: "NodeList",          support: true},
            "cloneNode":                        {type: "function" },
            "compareDocumentPosition":          {type: "function" },
            "contains":                         {type: "function" },
            "firstChild":                       {type: "DocumentType" },
            "hasChildNodes":                    {type: "function" },
            "insertBefore":                     {type: "function" },
            "isConnected":                      {type: "boolean" },
            "isDefaultNamespace":               {type: "function" },
            "isEqualNode":                      {type: "function" },
            "isSameNode":                       {type: "function" },
            "lastChild":                        {type: "HTMLHtmlElement" },
            "lookupNamespaceURI":               {type: "function" },
            "lookupPrefix":                     {type: "function" },
            "nextSibling":                      {type: "Null" },
            "nodeName":                         {type: "string" },
            "nodeType":                         {type: "number",            support: true },
            "nodeValue":                        {type: "Null" },
            "normalize":                        {type: "function" },
            "ownerDocument":                    {type: "Null" },
            "parentElement":                    {type: "Null" },
            "parentNode":                       {type: "Null" },
            "previousSibling":                  {type: "Null" },
            "removeChild":                      {type: "function" },
            "replaceChild":                     {type: "function" },
            "textContent":                      {type: "Null" }
        },
        "EventTarget": {
            "addEventListener":                 {type: "function" },
            "dispatchEvent":                    {type: "function",          support: true },
            "removeEventListener":              {type: "function" }
        }
    }
})